<?php
/**
 * Import Unit Relationships from Accounting Data
 * 
 * Purpose: Import 2,008 unit relationships to kontrak_unit table
 * Source: unit_to_contract_mapping.csv (generated by extract_unique_contracts.php)
 * Mapping: kontrak_id_mapping.json (generated by import_kontrak_from_accounting.php)
 */

$db = new mysqli('localhost', 'root', '', 'optima_ci');
if ($db->connect_error) {
    die("Connection failed: " . $db->connect_error);
}

echo "=== IMPORT UNIT RELATIONSHIPS ===\n\n";

$mapping_file = 'unit_to_contract_mapping.csv';
$kontrak_id_file = 'kontrak_id_mapping.json';

// Check prerequisites
if (!file_exists($mapping_file)) {
    die("ERROR: $mapping_file not found!\nPlease run extract_unique_contracts.php first.\n");
}

if (!file_exists($kontrak_id_file)) {
    die("ERROR: $kontrak_id_file not found!\nPlease run import_kontrak_from_accounting.php first.\n");
}

// Load kontrak_id mapping
$kontrak_mapping = json_decode(file_get_contents($kontrak_id_file), true);
echo "Loaded kontrak ID mapping: " . count($kontrak_mapping) . " contracts\n";

// Read unit mappings
echo "Reading unit mappings from $mapping_file...\n";
$handle = fopen($mapping_file, 'r');
fgetcsv($handle, 0, ';', '"', ''); // Skip header

$unit_relationships = [];
while (($row = fgetcsv($handle, 0, ';', '"', '')) !== false) {
    if (count($row) < 4) continue;
    
    $unit_relationships[] = [
        'contract_key' => $row[0],
        'unit_id' => $row[1],
        'customer_location_id' => $row[2],
        'harga_sewa' => $row[3],
        'unit_delivered_date' => $row[4] ?? ''
    ];
}
fclose($handle);

echo "Total unit relationships to import: " . count($unit_relationships) . "\n\n";

// Date conversion helper
function convertDate($dateStr) {
    if (empty($dateStr)) return null;
    
    $dateStr = trim($dateStr);
    
    // DD/MM/YYYY
    if (preg_match('/^(\d{2})\/(\d{2})\/(\d{4})$/', $dateStr, $m)) {
        if (checkdate($m[2], $m[1], $m[3])) {
            return "{$m[3]}-{$m[2]}-{$m[1]}";
        }
    }
    
    // MM/DD/YYYY
    if (preg_match('/^(\d{2})\/(\d{2})\/(\d{4})$/', $dateStr, $m)) {
        if (checkdate($m[1], $m[2], $m[3])) {
            return "{$m[3]}-{$m[1]}-{$m[2]}";
        }
    }
    
    // MM/DD/YY
    if (preg_match('/^(\d{2})\/(\d{2})\/(\d{2})$/', $dateStr, $m)) {
        $year = '20' . $m[3];
        if (checkdate($m[1], $m[2], $year)) {
            return "$year-{$m[1]}-{$m[2]}";
        }
    }
    
    return null;
}

// Import unit relationships
echo "Importing unit relationships...\n";

$inserted = 0;
$failed = 0;
$errors = [];
$missing_kontrak = [];
$missing_units = [];

foreach ($unit_relationships as $rel) {
    // Get kontrak_id from mapping
    if (!isset($kontrak_mapping[$rel['contract_key']])) {
        $missing_kontrak[] = $rel['contract_key'];
        $failed++;
        continue;
    }
    
    $kontrak_id = $kontrak_mapping[$rel['contract_key']];
    
    // Skip if unit_id is empty or not numeric
    if (empty($rel['unit_id']) || !is_numeric($rel['unit_id'])) {
        $failed++;
        continue;
    }
    
    // Validate unit_id exists
    $unit_id = (int)$rel['unit_id'];
    $unit_check = $db->query("SELECT id_inventory_unit FROM inventory_unit WHERE id_inventory_unit = $unit_id");
    if ($unit_check->num_rows === 0) {
        $missing_units[] = $unit_id;
        $failed++;
        continue;
    }
    
    // Get kontrak dates for this relationship
    $kontrak_data = $db->query("SELECT tanggal_mulai, tanggal_berakhir, status FROM kontrak WHERE id = $kontrak_id")->fetch_object();
    
    $tanggal_mulai = $kontrak_data->tanggal_mulai;
    $tanggal_selesai = $kontrak_data->tanggal_berakhir;
    $status = $kontrak_data->status === 'ACTIVE' ? 'ACTIVE' : 'TEMP_ACTIVE';
    
    // Validate and sanitize harga_sewa
    $harga_sewa = !empty($rel['harga_sewa']) && is_numeric($rel['harga_sewa']) ? (float)$rel['harga_sewa'] : 0;
    
    // Validate and sanitize customer_location_id
    $customer_location_id = !empty($rel['customer_location_id']) && is_numeric($rel['customer_location_id']) ? (int)$rel['customer_location_id'] : null;
    
    // Use delivered date if available and kontrak has dates
    $delivered_date = convertDate($rel['unit_delivered_date']);
    if ($delivered_date && $tanggal_mulai) {
        // Unit deployment date might differ from contract start
        // Keep contract dates for consistency
    }
    
    $sql = "INSERT INTO kontrak_unit (
        kontrak_id,
        unit_id,
        customer_location_id,
        harga_sewa,
        tanggal_mulai,
        tanggal_selesai,
        status,
        is_spare,
        created_at
    ) VALUES (
        $kontrak_id,
        $unit_id,
        " . ($customer_location_id ? $customer_location_id : 'NULL') . ",
        $harga_sewa,
        " . ($tanggal_mulai ? "'$tanggal_mulai'" : 'NULL') . ",
        " . ($tanggal_selesai ? "'$tanggal_selesai'" : 'NULL') . ",
        '$status',
        0,
        NOW()
    )";
    
    try {
        if ($db->query($sql)) {
            $inserted++;
            
            if ($inserted % 100 == 0) {
                echo "  Imported $inserted unit relationships...\n";
            }
        } else {
            $failed++;
            $errors[] = [
                'unit_id' => $unit_id,
                'kontrak_id' => $kontrak_id,
                'error' => $db->error
            ];
        }
    } catch (mysqli_sql_exception $e) {
        $failed++;
        $errors[] = [
            'unit_id' => $unit_id,
            'kontrak_id' => $kontrak_id,
            'error' => $e->getMessage()
        ];
        
        // Show duplicate errors as warnings instead of fatal
        if (strpos($e->getMessage(), 'Duplicate entry') !== false) {
            // Skip duplicate silently
        }
    }
}

echo "\n=== IMPORT SUMMARY ===\n";
echo "Total relationships processed: " . count($unit_relationships) . "\n";
echo "Successfully imported: $inserted\n";
echo "Failed: $failed\n";

if (count($missing_kontrak) > 0) {
    echo "\nMissing kontrak mappings: " . count(array_unique($missing_kontrak)) . "\n";
    echo "  (contract_keys not found in kontrak_id_mapping.json)\n";
}

if (count($missing_units) > 0) {
    echo "\nMissing units: " . count(array_unique($missing_units)) . " unique unit IDs\n";
    echo "  Sample missing units: " . implode(', ', array_slice(array_unique($missing_units), 0, 10)) . "\n";
}

if (count($errors) > 0 && count($errors) <= 10) {
    echo "\nSQL Errors:\n";
    foreach ($errors as $err) {
        echo "  - Unit {$err['unit_id']}, Kontrak {$err['kontrak_id']}: {$err['error']}\n";
    }
}

// Verify import
$final_count = $db->query("SELECT COUNT(*) as cnt FROM kontrak_unit")->fetch_object()->cnt;
$active_count = $db->query("SELECT COUNT(*) as cnt FROM kontrak_unit WHERE status = 'ACTIVE'")->fetch_object()->cnt;

echo "\n=== VERIFICATION ===\n";
echo "Total kontrak_unit in database: $final_count\n";
echo "  ACTIVE: $active_count\n";

// Check for orphans
$orphan_check = $db->query("
    SELECT COUNT(*) as cnt 
    FROM kontrak_unit ku 
    LEFT JOIN kontrak k ON ku.kontrak_id = k.id 
    WHERE k.id IS NULL
")->fetch_object()->cnt;

if ($orphan_check > 0) {
    echo "\n⚠ WARNING: Found $orphan_check orphan kontrak_unit records (no matching kontrak)\n";
} else {
    echo "\n✓ No orphan records found\n";
}

echo "\n✓ Kontrak_unit import complete.\n";

$db->close();
