<?php
/**
 * Import Unique Contracts from Accounting Data
 * 
 * Purpose: Import 348 unique contracts to kontrak table
 * Source: kontrak_from_accounting.csv (generated by extract_unique_contracts.php)
 * Strategy: Insert with foreign key validation, track kontrak_id mapping
 */

$db = new mysqli('localhost', 'root', '', 'optima_ci');
if ($db->connect_error) {
    die("Connection failed: " . $db->connect_error);
}

echo "=== IMPORT UNIQUE CONTRACTS ===\n\n";

$input_file = 'kontrak_from_accounting.csv';
if (!file_exists($input_file)) {
    die("ERROR: File $input_file not found!\nPlease run extract_unique_contracts.php first.\n");
}

// Check if table is empty
$count_check = $db->query("SELECT COUNT(*) as cnt FROM kontrak")->fetch_object()->cnt;
if ($count_check > 0) {
    echo "WARNING: kontrak table has $count_check rows!\n";
    echo "This script expects an empty table after TRUNCATE.\n";
    
    // Support non-interactive mode
    if (isset($argv[1]) && $argv[1] === '--force') {
        echo "Running in non-interactive mode (--force flag detected), continuing...\n";
    } else {
        echo "Do you want to continue? (yes/no): ";
        $confirm = trim(fgets(STDIN));
        if (strtolower($confirm) !== 'yes') {
            die("Aborted by user.\n");
        }
    }
}

echo "Reading contracts from $input_file...\n";

$handle = fopen($input_file, 'r');
$header = fgetcsv($handle, 0, ';', '"', ''); // Skip header

$contracts = [];
while (($row = fgetcsv($handle, 0, ';', '"', '')) !== false) {
    if (count($row) < 12) continue;
    
    $contracts[] = [
        'customer_id' => $row[0],
        'no_kontrak' => $row[1],
        'customer_po_number' => $row[2],
        'rental_type' => $row[3],
        'jenis_sewa' => $row[4],
        'billing_method' => $row[5],
        'tanggal_mulai' => $row[6] ?: null,
        'tanggal_berakhir' => $row[7] ?: null,
        'nilai_total' => $row[8],
        'total_units' => $row[9],
        'status' => $row[10],
        'contract_key' => $row[11]
    ];
}
fclose($handle);

echo "Total contracts to import: " . count($contracts) . "\n\n";

// Validate foreign keys
echo "Validating foreign keys...\n";
$invalid_customers = [];
$invalid_locations = [];

foreach ($contracts as $contract) {
    // Validate customer
    $customer_check = $db->query("SELECT id FROM customers WHERE id = {$contract['customer_id']}");
    if ($customer_check->num_rows === 0) {
        $invalid_customers[] = $contract['customer_id'];
    }
}

if (count($invalid_customers) > 0) {
    echo "ERROR: Invalid customer_ids found: " . implode(', ', array_unique($invalid_customers)) . "\n";
    die("Please fix customer_ids before importing.\n");
}

echo "✓ All foreign keys valid\n\n";

// Import contracts
echo "Importing contracts...\n";

$kontrak_id_mapping = []; // contract_key => kontrak.id
$inserted = 0;
$failed = 0;
$errors = [];

foreach ($contracts as $contract) {
    $sql = "INSERT INTO kontrak (
        customer_id,
        no_kontrak,
        customer_po_number,
        rental_type,
        jenis_sewa,
        billing_method,
        tanggal_mulai,
        tanggal_berakhir,
        nilai_total,
        total_units,
        status,
        dibuat_pada,
        diperbarui_pada
    ) VALUES (
        {$contract['customer_id']},
        '" . $db->real_escape_string($contract['no_kontrak']) . "',
        " . ($contract['customer_po_number'] ? "'" . $db->real_escape_string($contract['customer_po_number']) . "'" : 'NULL') . ",
        '" . $contract['rental_type'] . "',
        '" . $contract['jenis_sewa'] . "',
        '" . $contract['billing_method'] . "',
        '" . ($contract['tanggal_mulai'] ? $contract['tanggal_mulai'] : '1900-01-01') . "',
        " . ($contract['tanggal_berakhir'] ? "'" . $contract['tanggal_berakhir'] . "'" : 'NULL') . ",
        {$contract['nilai_total']},
        {$contract['total_units']},
        '" . $contract['status'] . "',
        NOW(),
        NOW()
    )";
    
    if ($db->query($sql)) {
        $kontrak_id = $db->insert_id;
        $kontrak_id_mapping[$contract['contract_key']] = $kontrak_id;
        $inserted++;
        
        if ($inserted % 50 == 0) {
            echo "  Imported $inserted contracts...\n";
        }
    } else {
        $failed++;
        $errors[] = [
            'contract' => $contract['no_kontrak'],
            'error' => $db->error
        ];
    }
}

echo "\n=== IMPORT SUMMARY ===\n";
echo "Total contracts processed: " . count($contracts) . "\n";
echo "Successfully imported: $inserted\n";
echo "Failed: $failed\n";

if (count($errors) > 0) {
    echo "\nErrors:\n";
    foreach ($errors as $err) {
        echo "  - {$err['contract']}: {$err['error']}\n";
    }
}

// Save mapping for kontrak_unit import
$mapping_file = 'kontrak_id_mapping.json';
file_put_contents($mapping_file, json_encode($kontrak_id_mapping, JSON_PRETTY_PRINT));
echo "\n✓ Kontrak ID mapping saved: $mapping_file\n";
echo "  (This file maps contract_key => kontrak.id for unit import)\n";

// Verify import
$final_count = $db->query("SELECT COUNT(*) as cnt FROM kontrak")->fetch_object()->cnt;
$active_count = $db->query("SELECT COUNT(*) as cnt FROM kontrak WHERE status = 'ACTIVE'")->fetch_object()->cnt;
$draft_count = $db->query("SELECT COUNT(*) as cnt FROM kontrak WHERE status = 'DRAFT'")->fetch_object()->cnt;

echo "\n=== VERIFICATION ===\n";
echo "Total kontrak in database: $final_count\n";
echo "  ACTIVE: $active_count\n";
echo "  DRAFT: $draft_count\n";
echo "\n✓ Kontrak import complete. Ready for kontrak_unit import.\n";

$db->close();
