#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
APP_DIR = ROOT / "app"
OUT_TXT = ROOT / "docs" / "RBAC_PERMISSION_CODE_KEYS.txt"
OUT_SQL = ROOT / "docs" / "RBAC_PERMISSION_CODE_KEYS.sql"

PATTERNS = [
    re.compile(r"hasPermission\(\s*'([^']+)'\s*"),
    re.compile(r"can_access\(\s*'([^']+)'\s*"),
    re.compile(r"canPerformAction\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*'([^']+)'\s*\)"),
    re.compile(r"canNavigateTo\(\s*'([^']+)'\s*,\s*'([^']+)'\s*\)"),
]


def normalize_from_groups(groups: tuple[str, ...]) -> str | None:
    if len(groups) == 1:
        key = groups[0].strip()
        if key and "." in key:
            return key
        return None
    if len(groups) == 2:
        module, page = groups[0].strip(), groups[1].strip()
        if module and page:
            return f"{module}.{page}.navigation"
        return None
    if len(groups) == 3:
        module, page, action = groups[0].strip(), groups[1].strip(), groups[2].strip()
        if module and page and action:
            return f"{module}.{page}.{action}"
    return None


def main() -> None:
    keys: set[str] = set()

    for path in APP_DIR.rglob("*.php"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for pattern in PATTERNS:
            for match in pattern.findall(text):
                groups = match if isinstance(match, tuple) else (match,)
                key = normalize_from_groups(groups)
                if key:
                    keys.add(key)

    sorted_keys = sorted(keys)
    OUT_TXT.write_text("\n".join(sorted_keys) + "\n", encoding="utf-8")

    sql_lines = [
        "-- Generated by tools/rbac/extract_permission_keys.py",
        "DROP TEMPORARY TABLE IF EXISTS tmp_code_permissions;",
        "CREATE TEMPORARY TABLE tmp_code_permissions (",
        "  key_name VARCHAR(191) NOT NULL PRIMARY KEY",
        ");",
        "",
    ]
    for key in sorted_keys:
        safe = key.replace("\\", "\\\\").replace("'", "''")
        sql_lines.append(f"INSERT IGNORE INTO tmp_code_permissions (key_name) VALUES ('{safe}');")
    sql_lines.append("")
    OUT_SQL.write_text("\n".join(sql_lines), encoding="utf-8")

    print(f"Wrote {OUT_TXT}")
    print(f"Wrote {OUT_SQL}")
    print(f"Total keys: {len(sorted_keys)}")


if __name__ == "__main__":
    main()
