<?= $this->extend('layouts/base') ?>

<?= $this->section('css') ?>
<style>
    .card-stats:hover { transform: translateY(-5px); box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15); }
    .table-card, .card-stats { border: none; border-radius: 15px; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1); }
    .modal-header { background: linear-gradient(135deg, #e9ecef 0%, #e9ecef 100%); color: white; border-radius: 15px 15px 0 0; }
    .filter-card.active { 
        transform: translateY(-3px); 
        box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2); 
        border: 2px solid #fff; 
    }
    .filter-card:hover { 
        transform: translateY(-5px); 
        box-shadow: 0 10px 35px rgba(0, 0, 0, 0.25); 
    }
</style>
<?= $this->endSection() ?>

<?= $this->section('content') ?>

    <!-- Statistics Cards -->
    <div class="row g-4 mb-4">
        <div class="col-xl-3 col-md-6"><div class="card card-stats bg-primary text-white h-100 filter-card" data-filter="all" style="cursor: pointer;"><div class="card-body"><h2 class="fw-bold mb-1" id="stat-total-spk">0</h2><h6 class="card-title text-uppercase small">Total SPK</h6></div></div></div>
        <div class="col-xl-3 col-md-6"><div class="card card-stats bg-warning text-white h-100 filter-card" data-filter="READY" style="cursor: pointer;"><div class="card-body"><h2 class="fw-bold mb-1" id="stat-ready">0</h2><h6 class="card-title text-uppercase small">Ready</h6></div></div></div>
        <div class="col-xl-3 col-md-6"><div class="card card-stats bg-info text-white h-100 filter-card" data-filter="IN_PROGRESS" style="cursor: pointer;"><div class="card-body"><h2 class="fw-bold mb-1" id="stat-in-progress">0</h2><h6 class="card-title text-uppercase small">In Progress</h6></div></div></div>
        <div class="col-xl-3 col-md-6"><div class="card card-stats bg-success text-white h-100 filter-card" data-filter="COMPLETED" style="cursor: pointer;"><div class="card-body"><h2 class="fw-bold mb-1" id="stat-completed">0</h2><h6 class="card-title text-uppercase small">Completed</h6></div></div></div>
    </div>

    <div class="card table-card mb-3">
        <div class="card-header d-flex flex-wrap gap-2 align-items-center justify-content-between">
            <h5 class="h5 mb-0 text-gray-800">Daftar SPK</h5>
            <div class="d-flex gap-2 align-items-center">
                <a class="btn btn-outline-secondary btn-sm" href="<?= base_url('operational/tracking') ?>">Tracking</a>
                <button class="btn btn-warning btn-sm" id="cleanupSpkZeroBtn" title="Hapus SPK dengan ID = 0">🧹 Cleanup SPK ID=0</button>
                <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#spkModal">Buat SPK</button>
            </div>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <div class="d-flex align-items-center gap-2">
                    <span>Show</span>
                    <select class="form-select form-select-sm" id="entriesPerPage" style="width: auto;">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <span>entries</span>
                </div>
                <div class="d-flex align-items-center gap-2">
                    <span>Search:</span>
                    <input type="text" class="form-control form-control-sm" id="spkSearch" placeholder="" style="width: 200px;">
                </div>
            </div>
            
            <div class="table-responsive">
                <table class="table table-sm mb-0" id="spkList">
                    <thead><tr><th>No. SPK</th><th>Jenis</th><th>Kontrak/PO</th><th>Nama Perusahaan</th><th>PIC</th><th>Kontak</th><th>Status</th><th>Total Unit</th><th>Aksi</th></tr></thead>
                    <tbody></tbody>
                </table>
            </div>
            
            <!-- Pagination and Info -->
            <div class="d-flex justify-content-between align-items-center mt-3">
                <div id="spkTableInfo">
                    Showing 0 to 0 of 0 entries
                </div>
                <nav>
                    <ul class="pagination pagination-sm mb-0" id="spkPagination">
                        <!-- Pagination will be generated by JavaScript -->
                    </ul>
                </nav>
            </div>
        </div>
    </div>

    <div class="modal fade" id="spkModal" tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header"><h6 class="modal-title">Buat SPK</h6><button class="btn-close" data-bs-dismiss="modal"></button></div>
                <form id="spkForm">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label class="form-label">Jenis SPK</label>
                            <select class="form-select form-select-sm w-auto" name="jenis_spk" required>
                                <option value="UNIT" selected>SPK Unit</option>
                                <option value="ATTACHMENT">SPK Attachment</option>
                                <option value="TUKAR">SPK Tukar</option>
                            </select>
                        </div>
                        
                        <!-- Step 1: Pilih Kontrak -->
                        <div class="mb-3">
                            <label class="form-label">Pilih Kontrak</label>
                            <select class="form-select" name="kontrak_id" id="kontrakSelect" required>
                                <option value="">-- Pilih Kontrak --</option>
                            </select>
                            <div class="form-text">Pilih kontrak yang sudah memiliki spesifikasi untuk membuat SPK</div>
                        </div>
                        
                        <!-- Step 2: Info Kontrak -->
                        <div id="kontrakInfoSection" style="display: none;">
                            <div class="card bg-light mb-3">
                                <div class="card-body">
                                    <h6 class="card-title">Info Kontrak</h6>
                                    <div class="row g-2">
                                        <div class="col-md-6">
                                            <label class="form-label">Pelanggan</label>
                                            <input class="form-control" name="pelanggan" id="inpPelanggan" readonly>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">No. Kontrak/PO</label>
                                            <input class="form-control" name="po_kontrak_nomor" id="inpPoKontrak" readonly>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">PIC (Person In Charge)</label>
                                            <input class="form-control" name="pic" id="inpPic">
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">Kontak PIC</label>
                                            <input class="form-control" name="kontak" id="inpKontak">
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">Lokasi</label>
                                            <input class="form-control" name="lokasi" id="inpLokasi">
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">Delivery Plan</label>
                                            <input type="date" class="form-control" name="delivery_plan">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Step 3: Pilih Spesifikasi -->
                        <div id="spesifikasiSection" style="display: none;">
                            <div class="mb-3">
                                <label class="form-label">Pilih Spesifikasi Unit</label>
                                <select class="form-select" name="kontrak_spesifikasi_id" id="spesifikasiSelect" required>
                                    <option value="">-- Pilih Spesifikasi --</option>
                                </select>
                                <div class="form-text">Pilih spesifikasi yang akan diproses dalam SPK ini</div>
                            </div>
                            
                            <!-- Detail Spesifikasi -->
                            <div id="spesifikasiDetail" style="display: none;">
                                <div class="card border-primary mb-3">
                                    <div class="card-header bg-primary text-black">
                                        <h6 class="mb-0">Detail Spesifikasi Terpilih</h6>
                                    </div>
                                    <div class="card-body">
                                        <div id="spesifikasiInfo">
                                            <!-- Will be populated with specification details -->
                                        </div>
                                        
                                        <div class="mt-3">
                                            <label class="form-label">Jumlah Unit untuk SPK ini</label>
                                            <div class="input-group">
                                                <input type="number" class="form-control" name="jumlah_unit" id="jumlahUnitSpk" min="1" required>
                                                <span class="input-group-text" id="maxUnitInfo">dari 0 tersedia</span>
                                            </div>
                                            <div class="form-text">Masukkan jumlah unit yang akan diproses dalam SPK ini</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="mt-3">
                            <label class="form-label">Catatan SPK</label>
                            <textarea class="form-control" name="catatan" rows="3" placeholder="Keterangan tambahan untuk SPK ini (opsional)"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">Tutup</button>
                        <button class="btn btn-primary" type="submit" id="submitSpkBtn" disabled>Buat SPK</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal Buat DI -->
    <div class="modal fade" id="diModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"><h6 class="modal-title">Buat Delivery Instruction</h6><button class="btn-close" data-bs-dismiss="modal"></button></div>
                <form id="diForm">
                    <div class="modal-body">
                        <input type="hidden" name="spk_id" id="diSpkId">
                        <div class="mb-2"><label class="form-label">No. SPK</label><input class="form-control" id="diNoSpk" readonly></div>
                        <div class="mb-2"><label class="form-label">Kontrak/PO</label><input class="form-control" id="diPoNo" readonly></div>
                        <div class="mb-2"><label class="form-label">Pelanggan</label><input class="form-control" id="diPelanggan" readonly></div>
                        <div class="mb-2"><label class="form-label">Lokasi</label><input class="form-control" id="diLokasi" readonly></div>
                        <div class="mb-2">
                            <label class="form-label">Item Terpilih (dari Service)</label>
                            <div class="alert alert-light border" id="diSelectedSummary">
                                <span class="text-muted">Belum ada ringkasan.</span>
                            </div>
                            <div id="diUnitsPick" class="mt-2" style="display:none">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <strong>Pilih Unit yang akan dikirim</strong>
                                    <div class="btn-group btn-group-sm">
                                        <button type="button" class="btn btn-outline-secondary" id="btnSelectAllUnits">Pilih Semua</button>
                                        <button type="button" class="btn btn-outline-secondary" id="btnClearUnits">Bersihkan</button>
                                    </div>
                                </div>
                                <div id="diUnitsList" class="border rounded p-2" style="max-height:200px; overflow:auto"></div>
                                <div class="form-text">Centang unit yang ingin dimasukkan ke DI ini.</div>
                            </div>
                        </div>
                        <div class="row g-2">
                            <div class="col-6"><label class="form-label">Tanggal Kirim</label><input type="date" class="form-control" name="tanggal_kirim"></div>
                            <div class="col-6 d-flex align-items-end"><span class="text-muted small">Opsional</span></div>
                        </div>
                        <div class="mt-2"><label class="form-label">Catatan</label><textarea class="form-control" name="catatan" rows="3" placeholder="Instruksi pengiriman (opsional)"></textarea></div>
                    </div>
                    <div class="modal-footer"><button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary" type="submit">Buat DI</button></div>
                </form>
            </div>
        </div>
    </div>

    <script>
    // Map status to Bootstrap badge classes per entity
    function statusBadge(entity, status){
        const s = (status||'').toUpperCase();
        const mapSPK = { SUBMITTED:'secondary', IN_PROGRESS:'info', READY:'success', DELIVERED:'primary', COMPLETED:'primary', CANCELLED:'danger' };
        const mapDI  = { SUBMITTED:'secondary', DISPATCHED:'info', ARRIVED:'success', CANCELLED:'danger' };
        const cls = (entity==='DI'?mapDI[s]:mapSPK[s]) || 'secondary';
        return `<span class="badge bg-${cls}">${status}</span>`;
    }
    
    // Global variables for filtering
    let allSpkData = [];
    let currentFilter = 'all';
    let currentSearchTerm = '';
    let currentPage = 1;
    let entriesPerPage = 10;
    
    // Update statistics cards
    function updateSpkStats(data) {
        const stats = {
            total: 0,
            inProgress: 0,
            ready: 0,
            completed: 0
        };
        
        (data || []).forEach(spk => {
            stats.total++;
            const status = (spk.status || '').toUpperCase();
            if (status === 'IN_PROGRESS') stats.inProgress++;
            else if (status === 'READY') stats.ready++;
            else if (status === 'COMPLETED' || status === 'DELIVERED') stats.completed++;
        });
        
        document.getElementById('stat-total-spk').textContent = stats.total;
        document.getElementById('stat-in-progress').textContent = stats.inProgress;
        document.getElementById('stat-ready').textContent = stats.ready;
        document.getElementById('stat-completed').textContent = stats.completed;
    }
    
    // Apply both status filter and search
    function applyFilters() {
        let filteredData = allSpkData;
        
        // Apply status filter
        if (currentFilter !== 'all') {
            filteredData = filteredData.filter(spk => {
                const status = (spk.status || '').toUpperCase();
                if (currentFilter === 'COMPLETED') {
                    return status === 'COMPLETED' || status === 'DELIVERED';
                }
                return status === currentFilter;
            });
        }
        
        // Apply search filter
        if (currentSearchTerm.trim() !== '') {
            const searchTerm = currentSearchTerm.toLowerCase();
            filteredData = filteredData.filter(spk => {
                return (spk.nomor_spk || '').toLowerCase().includes(searchTerm) ||
                       (spk.pelanggan || '').toLowerCase().includes(searchTerm) ||
                       (spk.po_kontrak_nomor || '').toLowerCase().includes(searchTerm) ||
                       (spk.pic || '').toLowerCase().includes(searchTerm) ||
                       (spk.kontak || '').toLowerCase().includes(searchTerm) ||
                       (spk.jenis_spk || '').toLowerCase().includes(searchTerm);
            });
        }
        
        renderSpkTable(filteredData);
        updatePagination(filteredData);
    }
    
    // Update pagination and info
    function updatePagination(data) {
        const totalEntries = data.length;
        const totalPages = Math.ceil(totalEntries / entriesPerPage);
        const startEntry = totalEntries === 0 ? 0 : (currentPage - 1) * entriesPerPage + 1;
        const endEntry = Math.min(currentPage * entriesPerPage, totalEntries);
        
        // Update info text
        document.getElementById('spkTableInfo').textContent = 
            `Showing ${startEntry} to ${endEntry} of ${totalEntries} entries` +
            (currentSearchTerm.trim() !== '' ? ' (filtered from ' + allSpkData.length + ' total entries)' : '');
        
        // Generate pagination
        const pagination = document.getElementById('spkPagination');
        pagination.innerHTML = '';
        
        if (totalPages <= 1) return;
        
        // Previous button
        const prevLi = document.createElement('li');
        prevLi.className = `page-item ${currentPage === 1 ? 'disabled' : ''}`;
        prevLi.innerHTML = `<a class="page-link" href="#" onclick="changePage(${currentPage - 1}); return false;">Previous</a>`;
        pagination.appendChild(prevLi);
        
        // Page numbers
        const startPage = Math.max(1, currentPage - 2);
        const endPage = Math.min(totalPages, currentPage + 2);
        
        if (startPage > 1) {
            const firstLi = document.createElement('li');
            firstLi.className = 'page-item';
            firstLi.innerHTML = `<a class="page-link" href="#" onclick="changePage(1); return false;">1</a>`;
            pagination.appendChild(firstLi);
            
            if (startPage > 2) {
                const dotsLi = document.createElement('li');
                dotsLi.className = 'page-item disabled';
                dotsLi.innerHTML = '<span class="page-link">...</span>';
                pagination.appendChild(dotsLi);
            }
        }
        
        for (let i = startPage; i <= endPage; i++) {
            const li = document.createElement('li');
            li.className = `page-item ${i === currentPage ? 'active' : ''}`;
            li.innerHTML = `<a class="page-link" href="#" onclick="changePage(${i}); return false;">${i}</a>`;
            pagination.appendChild(li);
        }
        
        if (endPage < totalPages) {
            if (endPage < totalPages - 1) {
                const dotsLi = document.createElement('li');
                dotsLi.className = 'page-item disabled';
                dotsLi.innerHTML = '<span class="page-link">...</span>';
                pagination.appendChild(dotsLi);
            }
            
            const lastLi = document.createElement('li');
            lastLi.className = 'page-item';
            lastLi.innerHTML = `<a class="page-link" href="#" onclick="changePage(${totalPages}); return false;">${totalPages}</a>`;
            pagination.appendChild(lastLi);
        }
        
        // Next button
        const nextLi = document.createElement('li');
        nextLi.className = `page-item ${currentPage === totalPages ? 'disabled' : ''}`;
        nextLi.innerHTML = `<a class="page-link" href="#" onclick="changePage(${currentPage + 1}); return false;">Next</a>`;
        pagination.appendChild(nextLi);
    }
    
    // Change page function
    function changePage(page) {
        currentPage = page;
        applyFilters();
    }
    
    // Filter SPK data based on status
    function filterSpkData(filter) {
        currentFilter = filter;
        currentPage = 1; // Reset to first page when filtering
        
        // Update active card styling
        document.querySelectorAll('.filter-card').forEach(card => {
            card.classList.remove('active');
        });
        document.querySelector(`[data-filter="${filter}"]`).classList.add('active');
        
        applyFilters();
    }
    
    // Render SPK table with given data
    function renderSpkTable(data) {
        const tb = document.querySelector('#spkList tbody');
        tb.innerHTML = '';
        
        // Calculate pagination
        const startIndex = (currentPage - 1) * entriesPerPage;
        const endIndex = startIndex + entriesPerPage;
        const paginatedData = data.slice(startIndex, endIndex);
        
        paginatedData.forEach(r=>{
            const tr = document.createElement('tr');
            const diBtn = (r.status === 'READY')
              ? `<button class="btn btn-sm btn-primary buat-di" data-id="${r.id}" data-spk='${JSON.stringify({id:r.id, nomor_spk:r.nomor_spk, po:r.po_kontrak_nomor, pelanggan:r.pelanggan, lokasi:r.lokasi}).replace(/'/g,"&apos;")}' title="Buat DI">Buat DI</button>`
              : '';
            const aksiBtn = diBtn || '<span class="text-muted">-</span>';
            tr.innerHTML = `<td><a href="#" onclick=\"openDetail(${r.id});return false;\">${r.nomor_spk}</a></td>`+
              `<td><span class=\"badge bg-dark\">${r.jenis_spk||'UNIT'}</span></td>`+
              `<td>${r.po_kontrak_nomor||'-'}</td>`+
              `<td>${r.pelanggan||'-'}</td>`+
              `<td>${r.pic||'-'}</td>`+
              `<td>${r.kontak||'-'}</td>`+
              `<td>${statusBadge('SPK', r.status)}</td>`+
              `<td>${r.jumlah_unit||'-'}</td>`+
              `<td>${aksiBtn}</td>`;
            tb.appendChild(tr);
        });
        
        // Wire up Buat DI buttons
        tb.querySelectorAll('.buat-di').forEach(btn=>{
            btn.addEventListener('click', (e)=>{
                const data = JSON.parse(e.currentTarget.getAttribute('data-spk').replace(/&apos;/g, "'"));
                document.getElementById('diSpkId').value = data.id || '';
                document.getElementById('diNoSpk').value = data.nomor_spk || '';
                document.getElementById('diPoNo').value = data.po || '';
                document.getElementById('diPelanggan').value = data.pelanggan || '';
                document.getElementById('diLokasi').value = data.lokasi || '';
                const diPicEl = document.getElementById('diPic');
                if (diPicEl) diPicEl.value = data.pic || '';
                const diKontakEl = document.getElementById('diKontak');
                if (diKontakEl) diKontakEl.value = data.kontak || '';
                // Load selected items summary or prepared units list
                const sum = document.getElementById('diSelectedSummary');
                const pickWrap = document.getElementById('diUnitsPick');
                const list = document.getElementById('diUnitsList');
                if (sum) { sum.innerHTML = '<span class="text-muted">Memuat item terpilih...</span>'; }
                if (pickWrap) { pickWrap.style.display = 'none'; list.innerHTML = ''; }
                fetch(`<?= base_url('marketing/spk/detail/') ?>${data.id}`).then(r=>r.json()).then(j=>{
                    if (!(j && j.success)) { if(sum) sum.innerHTML = '<span class="text-danger">Gagal memuat ringkasan item.</span>'; return; }
                    const s = j.spesifikasi || {};
                    // If prepared_units_detail exists (multi-unit), render selectable list
                    const details = Array.isArray(s.prepared_units_detail) ? s.prepared_units_detail : [];
                    if (details.length > 0 && pickWrap && list) {
                        pickWrap.style.display = 'block';
                        list.innerHTML = details.map((it,idx)=>{
                            const label = (it.unit_label || `${it.no_unit||'-'} - ${it.merk_unit||'-'} ${it.model_unit||''}`);
                            const sn = it.serial_number ? ` [SN: ${it.serial_number}]` : '';
                            return `<div class=\"form-check\"><input class=\"form-check-input di-unit-check\" type=\"checkbox\" value=\"${it.unit_id}\" id=\"di_unit_${it.unit_id}\" checked><label class=\"form-check-label\" for=\"di_unit_${it.unit_id}\">${idx+1}. ${label}${sn}</label></div>`;
                        }).join('');
                        // Summary
                        if (sum) sum.innerHTML = `<span class=\"text-success\">${details.length} unit disiapkan oleh Service. Silakan pilih yang akan dikirim.</span>`;
                        // Select all / clear
                        const btnAll = document.getElementById('btnSelectAllUnits');
                        const btnClr = document.getElementById('btnClearUnits');
                        if (btnAll) btnAll.onclick = ()=>{ document.querySelectorAll('.di-unit-check').forEach(ch=>ch.checked=true); };
                        if (btnClr) btnClr.onclick = ()=>{ document.querySelectorAll('.di-unit-check').forEach(ch=>ch.checked=false); };
                    } else {
                        // Fallback to legacy single selected summary
                        const u = s.selected && s.selected.unit ? s.selected.unit : null;
                        const a = s.selected && s.selected.attachment ? s.selected.attachment : null;
                        const unit = u ? `${u.no_unit||'-'} - ${u.merk_unit||'-'} ${u.model_unit||''} @ ${u.lokasi_unit||'-'}${u.serial_number?` [SN: ${u.serial_number}]`:''}` : null;
                        const att  = a ? `${a.tipe||'-'} ${a.merk||''} ${a.model||''}${a.sn_attachment?` [SN: ${a.sn_attachment}]`:''}${a.lokasi_penyimpanan?` @ ${a.lokasi_penyimpanan}`:''}` : null;
                        const html = `<ul class=\"mb-0\">${unit?`<li>Unit: ${unit}</li>`:''}${att?`<li>Attachment: ${att}</li>`:''}</ul>`;
                        if (sum) sum.innerHTML = (unit || att) ? html : '<span class="text-muted">Belum ada item yang ditetapkan Service.</span>';
                    }
                });
                const modal = new bootstrap.Modal(document.getElementById('diModal'));
                modal.show();
            });
        });
    }
    
    function loadSpk(){
        fetch('<?= base_url('marketing/spk/list') ?>').then(r=>r.json()).then(j=>{
            const data = j.data || [];
            allSpkData = data; // Store for filtering
            
            // Update statistics
            updateSpkStats(data);
            
            // Apply current filters
            applyFilters();
        });
    }
    function loadKontrakOptions(q){
        const url = new URL('<?= base_url('marketing/spk/kontrak-options') ?>', window.location.origin);
        if(q) url.searchParams.set('q', q);
        const jenisSel = document.querySelector('select[name="jenis_spk"]');
        const jenis = jenisSel ? jenisSel.value : 'UNIT';
        const kontrakStatus = (jenis === 'TUKAR') ? 'Aktif' : 'Pending';
        url.searchParams.set('status', kontrakStatus);
        fetch(url).then(r=>r.json()).then(j=>{
            const dl = document.getElementById('kontrakOptions');
            dl.innerHTML = '';
            (j.data||[]).forEach(opt=>{
                const o = document.createElement('option');
                o.value = opt.no_po_marketing || opt.no_kontrak || '';
                o.label = opt.label;
                dl.appendChild(o);
            });
        });
    }
    function loadMonitoring(){
        fetch('<?= base_url('marketing/spk/monitoring') ?>').then(r=>r.json()).then(j=>{
            const tb = document.querySelector('#monitoringTable tbody');
            if (!tb) return; // Skip if monitoring table doesn't exist
            tb.innerHTML = '';
            (j.data||[]).forEach(r=>{
                const tr = document.createElement('tr');
                const fmt = (v)=> v==null?0:v;
                tr.innerHTML = `
                    <td>${r.no_kontrak||'-'}</td>
                    <td>${r.no_po_marketing||'-'}</td>
                    <td>${r.pelanggan||'-'}</td>
                    <td>${r.lokasi||'-'}</td>
                    <td><span class="badge bg-dark">${fmt(r.total_spk)}</span></td>
                    <td><span class="badge bg-secondary">${fmt(r.submitted)}</span></td>
                    <td><span class="badge bg-info">${fmt(r.in_progress)}</span></td>
                    <td><span class="badge bg-warning">${fmt(r.ready)}</span></td>
                    <td><span class="badge bg-success">${fmt(r.delivered)}</span></td>
                    <td><span class="badge bg-danger">${fmt(r.cancelled)}</span></td>
                    <td>${r.last_update||'-'}</td>`;
                tb.appendChild(tr);
            });
        });
    }
    document.addEventListener('DOMContentLoaded',()=>{
    // Add global error handler for better debugging
    window.addEventListener('error', function(e) {
        console.error('Global error caught:', e.error, e.filename, e.lineno, e.colno);
    });
    
    window.addEventListener('unhandledrejection', function(e) {
        console.error('Unhandled promise rejection:', e.reason);
    });

    loadSpk();
    loadKontrakOptions('');
    loadMonitoring();
    
    // Add filter card click listeners
    document.querySelectorAll('.filter-card').forEach(card => {
        card.addEventListener('click', (e) => {
            const filter = e.currentTarget.getAttribute('data-filter');
            filterSpkData(filter);
        });
    });
    
    // Add search functionality
    const spkSearchInput = document.getElementById('spkSearch');
    if (spkSearchInput) {
        spkSearchInput.addEventListener('input', (e) => {
            currentSearchTerm = e.target.value;
            currentPage = 1; // Reset to first page when searching
            applyFilters();
        });
    }
    
    // Add entries per page functionality
    const entriesSelect = document.getElementById('entriesPerPage');
    if (entriesSelect) {
        entriesSelect.addEventListener('change', (e) => {
            entriesPerPage = parseInt(e.target.value);
            currentPage = 1; // Reset to first page when changing entries per page
            applyFilters();
        });
    }
    
    // Add cleanup SPK ID=0 functionality
    const cleanupBtn = document.getElementById('cleanupSpkZeroBtn');
    if (cleanupBtn) {
        cleanupBtn.addEventListener('click', () => {
            if (confirm('Apakah Anda yakin ingin menghapus semua SPK dengan ID = 0? Tindakan ini tidak dapat dibatalkan.')) {
                fetch('<?= base_url('marketing/spk/cleanup-zero') ?>', {
                    method: 'POST',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({})
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert(`Cleanup berhasil!\nDitemukan: ${data.found_records} record\nDihapus: ${data.deleted_records} SPK + ${data.deleted_history} status history`);
                        loadSpk(); // Reload the SPK list
                        loadMonitoring(); // Reload monitoring data
                    } else {
                        alert('Cleanup gagal: ' + data.message);
                    }
                })
                .catch(error => {
                    console.error('Cleanup error:', error);
                    alert('Terjadi kesalahan saat cleanup: ' + error.message);
                });
            }
        });
    }
    
    // Set default active filter (all)
    document.querySelector('[data-filter="all"]').classList.add('active');
    
    const kontrakInput = document.querySelector('input[name="po_kontrak_nomor"]');
    const pelangganInput = document.getElementById('inpPelanggan');
    const lokasiInput = document.getElementById('inpLokasi');
    kontrakInput.addEventListener('input', (e) => {
            const v = e.target.value.trim();
            // fetch as user types (debounce-lite)
            loadKontrakOptions(v);
            // try to find matching option and autofill pelanggan & lokasi from dataset
            const dl = document.getElementById('kontrakOptions');
            const match = Array.from(dl.options).find(o => o.value === v);
            if (match) {
                // We can't store custom data in datalist options cross-browser reliably; parse from label first
                // Label format: "<no kontrak> (<no po>) - <pelanggan>"
                if (match.label) {
                    const parts = match.label.split(' - ');
                    if (parts[1]) {
                        pelangganInput.value = parts[1];
                    }
                }
            }
        });
        // Lokasi mengikuti perubahan Pelanggan secara langsung
        pelangganInput.addEventListener('input', ()=>{ /* do not mirror lokasi automatically anymore */ });

        // Override lokasi based on kontrak lookup when focus leaves kontrak field (fetch selected option’s lokasi via API)
        kontrakInput.addEventListener('change', () => {
            const v = kontrakInput.value.trim();
            const url = new URL('<?= base_url('marketing/spk/kontrak-options') ?>', window.location.origin);
            if (v) url.searchParams.set('q', v);
            const jenisSel = document.querySelector('select[name="jenis_spk"]');
            const jenis = jenisSel ? jenisSel.value : 'UNIT';
            url.searchParams.set('status', (jenis === 'TUKAR') ? 'Aktif' : 'Pending');
            fetch(url).then(r=>r.json()).then(j=>{
                const rows = j.data||[];
                // Try exact match by no_po_marketing or no_kontrak
                const exact = rows.find(x => x.no_po_marketing === v || x.no_kontrak === v);
                if (exact) {
                    if (exact.pelanggan) pelangganInput.value = exact.pelanggan;
                    if (exact.lokasi) lokasiInput.value = exact.lokasi;
                }
            });
        });

        // New SPK workflow based on contract specifications
        const kontrakSelect = document.getElementById('kontrakSelect');
        const spesifikasiSelect = document.getElementById('spesifikasiSelect');
        const jumlahUnitInput = document.getElementById('jumlahUnitSpk');
        
        console.log('Elements found:', {
            kontrakSelect: !!kontrakSelect,
            spesifikasiSelect: !!spesifikasiSelect, 
            jumlahUnitInput: !!jumlahUnitInput
        });
        
        // Check URL parameters for pre-selected specification
        const urlParams = new URLSearchParams(window.location.search);
        const preSelectedSpekId = urlParams.get('spesifikasi_id');
        
        // Load available contracts with specifications
        function loadAvailableKontraks() {
            fetch('<?= base_url('marketing/kontrak/get-active-contracts') ?>', {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    let options = '<option value="">-- Pilih Kontrak --</option>';
                    if (data.success && data.data) {
                        data.data.forEach(kontrak => {
                            options += `<option value="${kontrak.id}">${kontrak.no_kontrak} - ${kontrak.pelanggan}</option>`;
                        });
                    }
                    if (kontrakSelect) {
                        kontrakSelect.innerHTML = options;
                    }
                    
                    // If we have a pre-selected specification, find and select its contract
                    if (preSelectedSpekId) {
                        findAndSelectKontrakBySpekId(preSelectedSpekId);
                    }
                })
                .catch(error => {
                    console.error('Error loading contracts:', error);
                    if (kontrakSelect) {
                        kontrakSelect.innerHTML = '<option value="">Error loading contracts</option>';
                    }
                });
        }
        
        // Find contract by specification ID and auto-select
        function findAndSelectKontrakBySpekId(spekId) {
            fetch(`<?= base_url('marketing/kontrak/find-by-spesifikasi/') ?>${spekId}`, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success && data.kontrak_id) {
                        // Select the contract
                        kontrakSelect.value = data.kontrak_id;
                        // Trigger change event to load contract info and specifications
                        kontrakSelect.dispatchEvent(new Event('change'));
                        
                        // After specifications load, select the target specification
                        setTimeout(() => {
                            if (spesifikasiSelect && spesifikasiSelect.querySelector(`option[value="${spekId}"]`)) {
                                spesifikasiSelect.value = spekId;
                                spesifikasiSelect.dispatchEvent(new Event('change'));
                            }
                        }, 1000);
                    }
                })
                .catch(error => {
                    console.error('Error finding contract for specification:', error);
                });
        }
        
        // Handle contract selection
        if (kontrakSelect) {
            kontrakSelect.addEventListener('change', function() {
                const kontrakId = this.value;
                console.log('Contract selected:', kontrakId);
                
                if (kontrakId) {
                    // Load contract info
                    loadKontrakInfo(kontrakId);
                    // Load specifications for this contract
                    loadKontrakSpesifikasiForSpk(kontrakId);
                    // Show contract info section
                    const kontrakInfoSection = document.getElementById('kontrakInfoSection');
                    const spesifikasiSection = document.getElementById('spesifikasiSection');
                    if (kontrakInfoSection) kontrakInfoSection.style.display = 'block';
                    if (spesifikasiSection) spesifikasiSection.style.display = 'block';
                } else {
                    // Hide sections
                    const kontrakInfoSection = document.getElementById('kontrakInfoSection');
                    const spesifikasiSection = document.getElementById('spesifikasiSection');
                    const spesifikasiDetail = document.getElementById('spesifikasiDetail');
                    const submitSpkBtn = document.getElementById('submitSpkBtn');
                    
                    if (kontrakInfoSection) kontrakInfoSection.style.display = 'none';
                    if (spesifikasiSection) spesifikasiSection.style.display = 'none';
                    if (spesifikasiDetail) spesifikasiDetail.style.display = 'none';
                    if (submitSpkBtn) submitSpkBtn.disabled = true;
                }
            });
        } else {
            console.error('kontrakSelect element not found');
        }
        
        // Load contract information
        function loadKontrakInfo(kontrakId) {
            fetch(`<?= base_url('marketing/kontrak/get-kontrak/') ?>${kontrakId}`, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success && data.data) {
                        const kontrak = data.data;
                        const inpPelanggan = document.getElementById('inpPelanggan');
                        const inpPoKontrak = document.getElementById('inpPoKontrak');
                        const inpPic = document.getElementById('inpPic');
                        const inpKontak = document.getElementById('inpKontak');
                        const inpLokasi = document.getElementById('inpLokasi');
                        
                        if (inpPelanggan) inpPelanggan.value = kontrak.pelanggan || '';
                        if (inpPoKontrak) inpPoKontrak.value = kontrak.no_kontrak || '';
                        if (inpPic) inpPic.value = kontrak.pic || '';
                        if (inpKontak) inpKontak.value = kontrak.kontak || '';
                        if (inpLokasi) inpLokasi.value = kontrak.lokasi || '';
                    }
                })
                .catch(error => {
                    console.error('Error loading contract info:', error);
                });
        }
        
        // Load specifications for selected contract
        function loadKontrakSpesifikasiForSpk(kontrakId) {
            fetch(`<?= base_url('marketing/kontrak/spesifikasi/') ?>${kontrakId}`, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    console.log('Specification data received:', data);
                    let options = '<option value="">-- Pilih Spesifikasi --</option>';
                    if (data.success && data.data) {
                        console.log('Processing ' + data.data.length + ' specifications');
                        data.data.forEach(spek => {
                            console.log('Processing spec:', spek);
                            const available = spek.jumlah_dibutuhkan - spek.jumlah_tersedia;
                            console.log('Available units:', available, 'dibutuhkan:', spek.jumlah_dibutuhkan, 'tersedia:', spek.jumlah_tersedia);
                            
                            // Show all specifications, not just those with available units
                            const spekDataEncoded = btoa(encodeURIComponent(JSON.stringify(spek)));
                            options += `<option value="${spek.id}" data-available="${available}" data-spek-encoded="${spekDataEncoded}">${spek.spek_kode} - ${spek.jumlah_dibutuhkan} dibutuhkan, ${spek.jumlah_tersedia} tersedia (${available > 0 ? available : 0} available)</option>`;
                        });
                        console.log('Generated options:', options);
                    } else {
                        console.log('No specification data or success=false:', data);
                        options = '<option value="">No specifications found</option>';
                    }
                    if (spesifikasiSelect) {
                        spesifikasiSelect.innerHTML = options;
                        console.log('Set spesifikasiSelect innerHTML');
                    } else {
                        console.error('spesifikasiSelect element not found');
                    }
                })
                .catch(error => {
                    console.error('Error loading specifications:', error);
                    if (spesifikasiSelect) {
                        spesifikasiSelect.innerHTML = '<option value="">Error loading specifications</option>';
                    }
                });
        }
        
        // Handle specification selection
        if (spesifikasiSelect) {
            spesifikasiSelect.addEventListener('change', function() {
                const spekId = this.value;
                const selectedOption = this.options[this.selectedIndex];
                console.log('Specification selected:', spekId, selectedOption);
                
                if (spekId && selectedOption) {
                    try {
                        const available = parseInt(selectedOption.getAttribute('data-available')) || 0;
                        const spekDataEncoded = selectedOption.getAttribute('data-spek-encoded') || '';
                        console.log('Encoded spec data:', spekDataEncoded);
                        
                        // Decode the spec data
                        const spekDataStr = decodeURIComponent(atob(spekDataEncoded));
                        console.log('Decoded spec data string:', spekDataStr);
                        
                        const spekData = JSON.parse(spekDataStr);
                        console.log('Parsed spec data:', spekData);
                        
                        // Show specification details
                        displaySpesifikasiDetail(spekData, available);
                        const spesifikasiDetail = document.getElementById('spesifikasiDetail');
                        if (spesifikasiDetail) spesifikasiDetail.style.display = 'block';
                        
                        // Set max unit input
                        if (jumlahUnitInput) {
                            jumlahUnitInput.max = available;
                            jumlahUnitInput.value = Math.min(1, available);
                        }
                        const maxUnitInfo = document.getElementById('maxUnitInfo');
                        if (maxUnitInfo) maxUnitInfo.textContent = `dari ${available} perlu diproses`;
                        
                        // Enable submit button if valid
                        validateSpkForm();
                    } catch (error) {
                        console.error('Error processing specification selection:', error);
                    }
                } else {
                    const spesifikasiDetail = document.getElementById('spesifikasiDetail');
                    const submitSpkBtn = document.getElementById('submitSpkBtn');
                    if (spesifikasiDetail) spesifikasiDetail.style.display = 'none';
                    if (submitSpkBtn) submitSpkBtn.disabled = true;
                }
            });
        } else {
            console.error('spesifikasiSelect element not found');
        }
        
        // Display specification details
        function displaySpesifikasiDetail(spek, available) {
            // Simple number formatting function
            function formatCurrency(amount) {
                if (!amount || isNaN(amount)) return '0';
                return parseInt(amount).toLocaleString('id-ID');
            }
            
            const detailHtml = `
                <div class="row g-2">
                    <div class="col-md-6">
                        <strong>Kode Spesifikasi:</strong> ${spek.spek_kode || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Departemen:</strong> ${spek.nama_departemen || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Tipe Unit:</strong> ${spek.tipe_unit_name || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Jenis:</strong> ${spek.tipe_jenis || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Merk/Model:</strong> ${spek.merk_unit || ''} ${spek.model_unit || ''}
                    </div>
                    <div class="col-md-6">
                        <strong>Kapasitas:</strong> ${spek.kapasitas_name || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Attachment:</strong> ${spek.attachment || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Baterai:</strong> ${spek.jenis_baterai || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Charger:</strong> ${spek.charger_id || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Mast:</strong> ${spek.mast_id || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Ban:</strong> ${spek.ban_id || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Roda:</strong> ${spek.roda_id || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Valve:</strong> ${spek.valve_id || '-'}
                    </div>
                    <div class="col-md-6">
                        <strong>Jumlah Unit:</strong> ${spek.jumlah_dibutuhkan || '-'}
                    </div>
                    <div class="col-md-12">
                        <strong>Aksesoris:</strong> ${spek.aksesoris || '-'}
                    </div>
                    ${spek.catatan_spek ? `<div class="col-12"><strong>Catatan:</strong> ${spek.catatan_spek}</div>` : ''}
                </div>
            `;
            const spesifikasiInfo = document.getElementById('spesifikasiInfo');
            if (spesifikasiInfo) {
                spesifikasiInfo.innerHTML = detailHtml;
            } else {
                console.error('spesifikasiInfo element not found');
            }
        }
        
        // Validate SPK form
        function validateSpkForm() {
            const kontrakId = kontrakSelect ? kontrakSelect.value : '';
            const spekId = spesifikasiSelect ? spesifikasiSelect.value : '';
            const jumlahUnit = parseInt(jumlahUnitInput ? jumlahUnitInput.value : 0) || 0;
            const maxUnit = parseInt(jumlahUnitInput ? jumlahUnitInput.max : 0) || 0;
            
            const isValid = kontrakId && spekId && jumlahUnit > 0 && jumlahUnit <= maxUnit;
            const submitBtn = document.getElementById('submitSpkBtn');
            if (submitBtn) submitBtn.disabled = !isValid;
        }
        
        // Handle input validation
        if (jumlahUnitInput) {
            jumlahUnitInput.addEventListener('input', validateSpkForm);
        }
        
        // Initialize on modal show
        const spkModal = document.getElementById('spkModal');
        if (spkModal) {
            spkModal.addEventListener('show.bs.modal', function() {
                loadAvailableKontraks();
                // Reset form
                document.getElementById('spkForm').reset();
                document.getElementById('kontrakInfoSection').style.display = 'none';
                document.getElementById('spesifikasiSection').style.display = 'none';
                document.getElementById('spesifikasiDetail').style.display = 'none';
                document.getElementById('submitSpkBtn').disabled = true;
            });
        }

        // Updated form submission to handle new workflow
        document.getElementById('spkForm').addEventListener('submit', (e)=>{
            e.preventDefault();
            const fd = new FormData(e.target);
            
            // Add specification ID for new workflow
            const spekId = spesifikasiSelect ? spesifikasiSelect.value : '';
            if (spekId) {
                fd.append('kontrak_spesifikasi_id', spekId);
            }
            
            fetch('<?= base_url('marketing/spk/create') ?>',{method:'POST', headers:{'X-Requested-With':'XMLHttpRequest'}, body:fd})
                .then(r=>r.json()).then(j=>{ 
                    if(j.success){ 
                        e.target.reset(); loadSpk(); loadMonitoring();
                        bootstrap.Modal.getInstance(document.getElementById('spkModal')).hide();
                        if (window.OptimaPro && typeof OptimaPro.showNotification==='function') OptimaPro.showNotification('SPK dibuat: ' + (j.nomor||''), 'success');
                        else if (typeof showNotification==='function') showNotification('SPK dibuat: ' + (j.nomor||''), 'success');
                    } else {
                        const msg = j.message || 'Gagal membuat SPK';
                        if (window.OptimaPro && typeof OptimaPro.showNotification==='function') OptimaPro.showNotification(msg, 'error');
                        else if (typeof showNotification==='function') showNotification(msg, 'error');
                    }
                });
        });
        // DI form submit
        document.getElementById('diForm').addEventListener('submit', (e)=>{
            e.preventDefault();
            const fd = new FormData(e.target);
            // If unit checkboxes exist, append unit_ids[]
            const checks = document.querySelectorAll('.di-unit-check');
            if (checks && checks.length) {
                const picked = Array.from(checks).filter(ch=>ch.checked).map(ch=>ch.value);
                if (picked.length === 0) {
                    alert('Pilih minimal satu unit untuk DI ini.');
                    return;
                }
                picked.forEach(v=> fd.append('unit_ids[]', v));
            }
            // spk_id already set; backend enforces COMPLETED status
            fetch('<?= base_url('marketing/di/create') ?>',{method:'POST', headers:{'X-Requested-With':'XMLHttpRequest'}, body:fd})
                .then(r=>r.json()).then(j=>{
                    if (j && j.success) {
                        bootstrap.Modal.getInstance(document.getElementById('diModal')).hide();
                        e.target.reset();
                        loadSpk();
                        loadMonitoring();
                        if (window.OptimaPro && typeof OptimaPro.showNotification==='function') OptimaPro.showNotification('DI dibuat: '+ (j.nomor||''), 'success');
                        else if (typeof showNotification==='function') showNotification('DI dibuat: '+ (j.nomor||''), 'success');
                        else alert('DI dibuat: '+ (j.nomor||''));
                    } else {
                        const msg = (j && j.message) ? j.message : 'Gagal membuat DI';
                        if (window.OptimaPro && typeof OptimaPro.showNotification==='function') OptimaPro.showNotification(msg, 'error');
                        else if (typeof showNotification==='function') showNotification(msg, 'error');
                        else alert(msg);
                    }
                });
        });
    });
    </script>
    <!-- Detail SPK Modal -->
    <div class="modal fade" id="spkDetailModal" tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header"><h6 class="modal-title">Detail SPK</h6><button class="btn-close" data-bs-dismiss="modal"></button></div>
                <div class="modal-body">
                    <div id="spkDetailBody"><p class="text-muted">Memuat...</p></div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" id="btnPrintPdf" href="#" target="_blank" rel="noopener">Print PDF</a>
                    <button class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>
    <script>
    function openDetail(id){
        const pdfBtn = document.getElementById('btnPrintPdf');
        if (pdfBtn) { pdfBtn.href = `<?= base_url('marketing/spk/print/') ?>${id}`; }
        const body = document.getElementById('spkDetailBody');
        body.innerHTML = '<p class="text-muted">Memuat...</p>';
        
        fetch(`<?= base_url('marketing/spk/detail/') ?>${id}`)
            .then(r => {
                if (!r.ok) {
                    throw new Error(`HTTP error! Status: ${r.status}`);
                }
                return r.json();
            })
            .then(j => {
                if (!j.success) { 
                    body.innerHTML = '<div class="text-danger">Gagal memuat detail</div>'; 
                    return; 
                }
            // Main data comes from j.data (the spk table data)
            const d = j.data || {};
            
            // Check if kontrak_spesifikasi_id exists in the main data
            const kontrakSpecId = d.kontrak_spesifikasi_id || null;
            
            // Specification data comes from j.spesifikasi (enriched data from the controller)
            const s = j.spesifikasi || {};
            
            // Get specification code from the provided spek_kode
            let specDisplay = '-';
            // Try to get specification code from different potential sources
            if (j.kontrak_spec && j.kontrak_spec.spek_kode) {
                specDisplay = j.kontrak_spec.spek_kode;
            } else if (s && s.spek_kode) {
                specDisplay = s.spek_kode;
            }
            
            // Process accessories from the spesifikasi JSON object
            let aksText = '-';
            // First try to get accessories from kontrak_spec if available
            if (j.kontrak_spec && j.kontrak_spec.aksesoris) {
                const aks = j.kontrak_spec.aksesoris;
                if (Array.isArray(aks) && aks.length > 0) {
                    aksText = aks.join(', ');
                } else if (typeof aks === 'string') {
                    try {
                        const parsed = JSON.parse(aks);
                        if (Array.isArray(parsed) && parsed.length > 0) {
                            aksText = parsed.join(', ');
                        } else {
                            aksText = aks;
                        }
                    } catch(e) {
                        aksText = aks;
                    }
                }
            // Fall back to spesifikasi.aksesoris
            } else if (s && s.aksesoris) {
                if (Array.isArray(s.aksesoris) && s.aksesoris.length > 0) {
                    aksText = s.aksesoris.join(', ');
                } else if (typeof s.aksesoris === 'string' && s.aksesoris.trim()) {
                    try {
                        const parsed = JSON.parse(s.aksesoris);
                        if (Array.isArray(parsed) && parsed.length > 0) {
                            aksText = parsed.join(', ');
                        } else {
                            aksText = s.aksesoris;
                        }
                    } catch(e) {
                        aksText = s.aksesoris;
                    }
                }
            }
            // Selected unit and attachment from controller response
            const u = s.selected && s.selected.unit ? s.selected.unit : null;
            const a = s.selected && s.selected.attachment ? s.selected.attachment : null;
            
            try {
                body.innerHTML = `
                    <div class="row g-2">
                        <div class="col-6"><strong>Jenis SPK:</strong> ${d.jenis_spk||'-'}</div>
                        <div class="col-6"><strong>No SPK:</strong> ${d.nomor_spk||'-'}</div>
                        <div class="col-6"><strong>Kontrak/PO:</strong> ${d.po_kontrak_nomor||'-'}</div>
                        <div class="col-6"><strong>Pelanggan:</strong> ${d.pelanggan||'-'}</div>
                        <div class="col-6"><strong>Lokasi:</strong> ${d.lokasi||'-'}</div>
                        <div class="col-6"><strong>Delivery Plan:</strong> ${d.delivery_plan||'-'}</div>
                        <div class="col-6"><strong>Pic:</strong> ${d.pic||'-'}</div>
                        <div class="col-6"><strong>Kontak:</strong> ${d.kontak||'-'}</div>
                        <div class="col-12"><hr></div>
                        <div class="col-12"><strong>Informasi Unit:</strong></div>
                        <div class="col-6"><strong>Spesifikasi:</strong> ${specDisplay}</div>
                        <div class="col-6"><strong>Total Unit:</strong> ${d.jumlah_unit || 0}</div>
                        <div class="col-6"><strong>Tipe (Jenis):</strong> ${s.tipe_jenis||'-'}</div>
                        <div class="col-6"><strong>Merk Unit:</strong> ${s.merk_unit||'-'}</div>
                        <div class="col-6"><strong>Valve:</strong> ${s.valve_id_name||'-'}</div>
                        <div class="col-6"><strong>Baterai (Jenis):</strong> ${s.jenis_baterai||'-'}</div>
                        <div class="col-6"><strong>Charger:</strong> ${s.charger_id_name||'-'}</div>
                        <div class="col-6"><strong>Attachment (Tipe):</strong> ${s.attachment_tipe||'-'}</div>
                        <div class="col-6"><strong>Roda:</strong> ${s.roda_id_name||'-'}</div>
                        <div class="col-6"><strong>Departemen:</strong> ${s.departemen_id_name||'-'}</div>
                        <div class="col-6"><strong>Kapasitas:</strong> ${s.kapasitas_id_name||'-'}</div>
                        <div class="col-6"><strong>Mast:</strong> ${s.mast_id_name||'-'}</div>
                        <div class="col-6"><strong>Ban:</strong> ${s.ban_id_name||'-'}</div>
                        <div class="col-12"><strong>Aksesoris:</strong> ${aksText}</div>
                        <div class="col-12"><hr></div>
                        <div class="col-12"><strong>Item Terpilih:</strong></div>
                        <div class="col-12" id="svcUnitDetailBlock">
                            ${u ? '<div class="text-muted">Memuat detail unit...</div>' : '<div class="text-muted">Unit: -</div>'}
                        </div>
                        ${a ? 
                          `<div class="col-12">
                            <div><strong>Attachment:</strong> 
                              ${a.tipe||'-'} ${a.merk||''} ${a.model||''}
                              ${a.sn_attachment ? ` [SN: ${a.sn_attachment}]` : ''}
                              ${a.lokasi_penyimpanan ? ` @ ${a.lokasi_penyimpanan}` : ''}
                            </div>
                           </div>` 
                          : ''}
                    </div>`;
            } catch(error) {
                body.innerHTML = `<div class="alert alert-danger">Error rendering SPK detail: ${error.message}</div>`;
                console.error('Error rendering SPK detail:', error);
                return;
            }
            
            // Load full unit detail if selected
			if (s.selected && s.selected.unit && s.selected.unit.id) {
				const esc = (str)=>{ if(str===null||str===undefined||str==='') return '-'; return String(str).replaceAll('<','&lt;').replaceAll('>','&gt;'); };
				fetch(`<?= base_url('warehouse/inventory/get-unit-full-detail/') ?>${s.selected.unit.id}`)
				    .then(r => {
				        if (!r.ok) {
				            throw new Error(`Error loading unit details: ${r.status} ${r.statusText}`);
				        }
				        return r.json();
				    })
				    .then(resp => {
					    const host = document.getElementById('svcUnitDetailBlock');
					    if(!host) return;
					    if(!(resp && resp.success && resp.data)){ 
					        host.innerHTML = '<div class="text-danger">Gagal memuat detail unit</div>'; 
					        return; 
					    }
					    const data = resp.data;
					    host.innerHTML = `
					    <div class="row g-2">
                            <div class="col-6"><strong>ID Unit</strong>: ${esc(data.id_inventory_unit)}</div>
                            <div class="col-6"><strong>Serial Number</strong>: ${esc(data.serial_number_po)}</div>
                            <div class="col-6"><strong>Merk</strong>: ${esc(data.merk_unit)}</div>
                            <div class="col-6"><strong>Model</strong>: ${esc(data.model_unit)}</div>
                            <div class="col-6"><strong>Jenis Unit</strong>: ${esc(data.nama_departemen)}</div>
                            <div class="col-6"><strong>Tipe Unit</strong>: ${esc(data.nama_tipe_unit)}</div>
                            <div class="col-6"><strong>Tahun</strong>: ${esc(data.tahun_po)}</div>
                            <div class="col-6"><strong>Kapasitas</strong>: ${esc(data.kapasitas_unit)}</div>
                            <div class="col-6"><strong>Tanggal Masuk</strong>: ${esc(data.tanggal_masuk)}</div>
                            <div class="col-12"><hr></div>
                            <div class="col-6"><strong>Attachment</strong>: ${esc(data.attachment_tipe || '-')}</div>
                            <div class="col-6"><strong>SN Attachment</strong>: ${esc(data.sn_attachment_po)}</div>
                            <div class="col-6"><strong>Mast</strong>: ${esc(data.tipe_mast)}</div>
                            <div class="col-6"><strong>SN Mast</strong>: ${esc(data.sn_mast_po)}</div>
                            <div class="col-6"><strong>Mesin</strong>: ${esc((data.merk_mesin||'-') + ' ' + (data.model_mesin||''))}</div>
                            <div class="col-6"><strong>SN Mesin</strong>: ${esc(data.sn_mesin_po)}</div>
                            <div class="col-6"><strong>Baterai</strong>: ${esc(data.tipe_baterai)}</div>
                            <div class="col-6"><strong>SN Baterai</strong>: ${esc(data.sn_baterai_po)}</div>
                            <div class="col-6"><strong>Charger</strong>: ${esc(data.tipe_charger)}</div>
                            <div class="col-6"><strong>SN Charger</strong>: ${esc(data.sn_charger_po)}</div>
                            <div class="col-6"><strong>Ban</strong>: ${esc(data.tipe_ban)}</div>
                            <div class="col-6"><strong>Roda</strong>: ${esc(data.tipe_roda)}</div>
                            <div class="col-6"><strong>Valve</strong>: ${esc(data.jumlah_valve)}</div>
                            <div class="col-6"><strong>Aksesoris</strong>: ${esc(data.aksesoris_unit)}</div>
                        </div>
                        <div class="col-12"><hr></div>
                        <div class="col-12"><strong>Catatan:</strong> ${esc(data.catatan_unit)}</div>
                        `;
				    })
				    .catch(error => {
				        const host = document.getElementById('svcUnitDetailBlock');
				        if (host) {
				            host.innerHTML = `<div class="alert alert-danger">Error loading unit details: ${error.message}</div>`;
				        }
				        console.error('Error loading unit details:', error);
				    });
			}
            
            // Show the modal after data is loaded
            const modal = document.getElementById('spkDetailModal');
            if (modal) {
                new bootstrap.Modal(modal).show();
            } else {
                console.error('SPK detail modal element not found');
            }
        }).catch(error => {
            body.innerHTML = `<div class="alert alert-danger">Error loading SPK details: ${error.message}</div>`;
            console.error('Error loading SPK details:', error);
            
            // Show the modal even on error
            const modal = document.getElementById('spkDetailModal');
            if (modal) {
                new bootstrap.Modal(modal).show();
            }
        });
    }
    </script>
    <style>
    /* Ensure the SPK modal body scrolls when content is long */
    #spkModal .modal-body { max-height: 70vh; overflow-y: auto; }
    </style>
</div>
<?= $this->endSection() ?>
