<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Auto-Generated Notification</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .email-wrapper {
            max-width: 650px;
            margin: 20px auto;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #28a745 0%, #1e7e34 100%);
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            font-weight: 600;
        }
        .header .icon {
            font-size: 48px;
            margin-bottom: 10px;
        }
        .content {
            padding: 30px 25px;
            background: #fff;
        }
        .content p {
            margin: 0 0 15px 0;
            color: #555;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: #f9f9f9;
            border-radius: 6px;
            overflow: hidden;
        }
        .info-table tr {
            border-bottom: 1px solid #e0e0e0;
        }
        .info-table tr:last-child {
            border-bottom: none;
        }
        .info-table th,
        .info-table td {
            padding: 12px 15px;
            text-align: left;
        }
        .info-table th {
            background: #28a745;
            color: white;
            font-weight: 600;
            width: 40%;
        }
        .info-table td {
            background: white;
            color: #333;
        }
        .info-table td strong {
            color: #28a745;
            font-size: 16px;
        }
        .success-box {
            background: #d4edda;
            border-left: 4px solid #28a745;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .success-box strong {
            color: #155724;
            display: block;
            margin-bottom: 8px;
            font-size: 16px;
        }
        .success-box p {
            margin: 5px 0;
            color: #155724;
            font-size: 14px;
        }
        .btn-primary {
            display: inline-block;
            padding: 12px 30px;
            background: #28a745;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-weight: 600;
            margin: 20px 0;
            transition: background 0.3s;
        }
        .btn-primary:hover {
            background: #1e7e34;
        }
        .btn-container {
            text-align: center;
            margin: 25px 0;
        }
        .footer {
            text-align: center;
            padding: 20px;
            background: #f8f9fa;
            color: #666;
            font-size: 13px;
            border-top: 1px solid #e0e0e0;
        }
        .footer p {
            margin: 5px 0;
        }
        .footer strong {
            color: #333;
        }
        .note {
            margin-top: 25px;
            padding: 15px;
            background: #d1ecf1;
            border-radius: 4px;
            font-size: 14px;
            color: #0c5460;
            border-left: 3px solid #17a2b8;
        }
        .note em {
            font-style: normal;
            font-weight: 600;
        }
        .status-badge {
            display: inline-block;
            padding: 5px 12px;
            background: #28a745;
            color: white;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 600;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="header">
            <div class="icon">✅</div>
            <h1>Invoice Auto-Generated Successfully</h1>
        </div>
        
        <div class="content">
            <p><strong>Dear Marketing Team,</strong></p>
            
            <p>This is a notification that an invoice has been automatically generated by the system for your contract. The invoice has been forwarded to the Accounting team for processing and will be sent to the customer shortly.</p>
            
            <table class="info-table">
                <tr>
                    <th>Invoice Number</th>
                    <td><strong><?= $invoice['invoice_number'] ?? 'N/A' ?></strong></td>
                </tr>
                <tr>
                    <th>Customer</th>
                    <td><?= $customer_name ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Contract/PO Number</th>
                    <td><?= $contract_number ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Invoice Amount</th>
                    <td><strong style="color: #28a745; font-size: 18px;">Rp <?= number_format($invoice['total_amount'] ?? 0, 0, ',', '.') ?></strong></td>
                </tr>
                <tr>
                    <th>DI Number</th>
                    <td><?= $di['di_number'] ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>DI Completed Date</th>
                    <td><?= isset($di['completed_at']) ? date('d F Y', strtotime($di['completed_at'])) : 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Auto-Generated</th>
                    <td><?= isset($invoice['created_at']) ? date('d F Y H:i', strtotime($invoice['created_at'])) : date('d F Y H:i') ?> WIB</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td><span class="status-badge">📨 Sent to Accounting</span></td>
                </tr>
            </table>
            
            <div class="success-box">
                <strong>✓ Invoice Processing Status:</strong>
                <p>✓ Invoice generated successfully by automation system</p>
                <p>✓ Accounting team has been notified via email</p>
                <p>✓ Invoice package preparation in progress</p>
                <p>✓ Customer will receive invoice shortly</p>
            </div>
            
            <div class="btn-container">
                <a href="<?= base_url('finance/invoices/' . ($invoice['id'] ?? '')) ?>" class="btn-primary">
                    📄 View Invoice Details
                </a>
            </div>
            
            <div class="note">
                <em>💡 FYI:</em> This invoice was automatically generated 30 days after delivery completion according to the standard billing cycle. If the customer has any questions about the invoice, they may contact you as the sales representative. You can coordinate with the Accounting team as needed.
            </div>
        </div>
        
        <div class="footer">
            <p><strong>PT Sarana Mitra Luas</strong></p>
            <p>Optima ERP System - Marketing Notification</p>
            <p>Generated: <?= date('d F Y H:i:s') ?> WIB</p>
            <p style="margin-top: 10px; font-size: 11px; color: #999;">
                This is an automated notification email. For inquiries, please contact the Accounting team.
            </p>
        </div>
    </div>
</body>
</html>
