<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Ready for Processing</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .email-wrapper {
            max-width: 650px;
            margin: 20px auto;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            font-weight: 600;
        }
        .header .icon {
            font-size: 48px;
            margin-bottom: 10px;
        }
        .content {
            padding: 30px 25px;
            background: #fff;
        }
        .content p {
            margin: 0 0 15px 0;
            color: #555;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: #f9f9f9;
            border-radius: 6px;
            overflow: hidden;
        }
        .info-table tr {
            border-bottom: 1px solid #e0e0e0;
        }
        .info-table tr:last-child {
            border-bottom: none;
        }
        .info-table th,
        .info-table td {
            padding: 12px 15px;
            text-align: left;
        }
        .info-table th {
            background: #007bff;
            color: white;
            font-weight: 600;
            width: 40%;
        }
        .info-table td {
            background: white;
            color: #333;
        }
        .info-table td strong {
            color: #007bff;
            font-size: 16px;
        }
        .alert-box {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .alert-box strong {
            color: #856404;
            display: block;
            margin-bottom: 8px;
            font-size: 16px;
        }
        .alert-box ul {
            margin: 10px 0 0 0;
            padding-left: 20px;
            color: #856404;
        }
        .alert-box ul li {
            margin: 5px 0;
        }
        .btn-primary {
            display: inline-block;
            padding: 12px 30px;
            background: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-weight: 600;
            margin: 20px 0;
            transition: background 0.3s;
        }
        .btn-primary:hover {
            background: #0056b3;
        }
        .btn-container {
            text-align: center;
            margin: 25px 0;
        }
        .footer {
            text-align: center;
            padding: 20px;
            background: #f8f9fa;
            color: #666;
            font-size: 13px;
            border-top: 1px solid #e0e0e0;
        }
        .footer p {
            margin: 5px 0;
        }
        .footer strong {
            color: #333;
        }
        .note {
            margin-top: 25px;
            padding: 15px;
            background: #e7f3ff;
            border-radius: 4px;
            font-size: 14px;
            color: #004085;
            border-left: 3px solid #007bff;
        }
        .note em {
            font-style: normal;
            font-weight: 600;
        }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="header">
            <div class="icon">🧾</div>
            <h1>Invoice Ready for Processing</h1>
        </div>
        
        <div class="content">
            <p><strong>Dear Accounting Team,</strong></p>
            
            <p>An invoice has been automatically generated by the Optima ERP system and is now ready for processing. Please review the details below and proceed with preparing the invoice package for the customer.</p>
            
            <table class="info-table">
                <tr>
                    <th>Invoice Number</th>
                    <td><strong><?= $invoice['invoice_number'] ?? 'N/A' ?></strong></td>
                </tr>
                <tr>
                    <th>Customer</th>
                    <td><?= $customer_name ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Contract/PO Number</th>
                    <td><?= $contract_number ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Invoice Amount</th>
                    <td><strong style="color: #28a745; font-size: 18px;">Rp <?= number_format($invoice['total_amount'] ?? 0, 0, ',', '.') ?></strong></td>
                </tr>
                <tr>
                    <th>DI Number</th>
                    <td><?= $di['di_number'] ?? 'N/A' ?></td>
                </tr>
                <tr>
                    <th>DI Completed Date</th>
                    <td><?= isset($di['completed_at']) ? date('d F Y', strtotime($di['completed_at'])) : 'N/A' ?></td>
                </tr>
                <tr>
                    <th>Invoice Generated</th>
                    <td><?= isset($invoice['created_at']) ? date('d F Y H:i', strtotime($invoice['created_at'])) : date('d F Y H:i') ?> WIB</td>
                </tr>
            </table>
            
            <div class="alert-box">
                <strong>⚠️ Action Required:</strong>
                <ul>
                    <li><strong>Step 1:</strong> Verify invoice details and accuracy in the system</li>
                    <li><strong>Step 2:</strong> Collect and attach all supporting documents (BAST, delivery proof, photos, etc.)</li>
                    <li><strong>Step 3:</strong> Prepare invoice package in proper format (PDF)</li>
                    <li><strong>Step 4:</strong> Send complete invoice package to customer</li>
                    <li><strong>Step 5:</strong> Update payment tracking status in system</li>
                </ul>
            </div>
            
            <div class="btn-container">
                <a href="<?= base_url('finance/invoices/' . ($invoice['id'] ?? '')) ?>" class="btn-primary">
                    📄 View Invoice in System
                </a>
            </div>
            
            <div class="note">
                <em>📌 Note:</em> This invoice was automatically generated 30 days after delivery completion as per company policy. If you have any questions or need assistance, please contact the Marketing team or system administrator.
            </div>
        </div>
        
        <div class="footer">
            <p><strong>PT Sarana Mitra Luas</strong></p>
            <p>Optima ERP System - Automated Invoice Notification</p>
            <p>Generated: <?= date('d F Y H:i:s') ?> WIB</p>
            <p style="margin-top: 10px; font-size: 11px; color: #999;">
                This is an automated email. Please do not reply directly to this message.
            </p>
        </div>
    </div>
</body>
</html>
