-- =====================================================
-- CLEAN INSERT: notification_rules
-- Description: Hapus semua data lama, insert data baru yang rapih
-- Date: 2026-03-13
-- =====================================================

-- Step 1: Backup dan hapus data lama (jika perlu backup dulu, comment ini)
-- Backup ke tabel sementara dulu
CREATE TABLE IF NOT EXISTS notification_rules_backup AS SELECT * FROM notification_rules;

-- Atau langsung hapus semua data
TRUNCATE TABLE notification_rules;

-- Step 2: Insert data baru yang rapih
-- Format: id, name, description, trigger_event, is_active, conditions, target_roles, target_divisions, target_departments, target_users, exclude_creator, title_template, message_template, category, type, priority, notification_style, url_template, delay_minutes, expire_days, created_by, created_at, updated_at, auto_include_superadmin, target_mixed, rule_description

INSERT INTO notification_rules (id, name, description, trigger_event, is_active, conditions, target_roles, target_divisions, target_departments, target_users, exclude_creator, title_template, message_template, category, type, priority, notification_style, url_template, delay_minutes, expire_days, created_by, created_at, updated_at, auto_include_superadmin, target_mixed, rule_description) VALUES

-- SPK (Work Order) Notifications
(1, 'SPK Baru - Marketing ke Service', 'Marketing membuat SPK baru untuk diproses Service', 'spk_created', 1, NULL, 'head_service,supervisor_service,admin_service_pusat,admin_service_area', 'Service', NULL, NULL, 1, 'SPK Baru: {{nomor_spk}}', 'SPK {{nomor_spk}} telah dibuat untuk {{pelanggan}}. Unit: {{unit_no}}. Departemen: {{department}}', 'spk', 'info', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Marketing ke Service - perlu diproses'),
(2, 'SPK Ditugaskan - Head ke Staff', 'Head Service menugaskan SPK ke Staff', 'spk_assigned', 1, NULL, 'staff_service,supervisor_service', 'Service', NULL, NULL, 1, 'SPK Ditugaskan: {{nomor_spk}}', 'SPK {{nomor_spk}} untuk {{pelanggan}} telah ditugaskan ke {{assigned_to}}', 'spk', 'info', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Head/Supervisor ke Staff'),
(3, 'SPK Dimulai - Staff mengerjakan', 'Staff Service mulai mengerjakan SPK', 'spk_in_progress', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'SPK Dimulai: {{nomor_spk}}', 'SPK {{nomor_spk}} untuk {{pelanggan}} sedang dikerjakan oleh {{handled_by}}', 'spk', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Staff ke Head/Supervisor'),
(4, 'SPK Selesai - Staff ke Head', 'Staff Service menyelesaikan SPK', 'spk_completed', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'SPK Selesai: {{nomor_spk}}', 'SPK {{nomor_spk}} untuk {{pelanggan}} telah selesai dikerjakan', 'spk', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Staff ke Head Marketing & Head Service'),
(5, 'SPK Dibatalkan', 'SPK dibatalkan', 'spk_cancelled', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'SPK Dibatalkan: {{nomor_spk}}', 'SPK {{nomor_spk}} untuk {{pelanggan}} telah dibatalkan. Alasan: {{reason}}', 'spk', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifikasi ke semua pihak'),
(6, 'SPK Ditolak - Service ke Marketing', 'SPK ditolak oleh Service', 'spk_rejected', 1, NULL, 'head_marketing,staff_marketing', 'Marketing', NULL, NULL, 1, 'SPK Ditolak: {{nomor_spk}}', 'SPK {{nomor_spk}} untuk {{pelanggan}} ditolak. Alasan: {{reason}}', 'spk', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Service ke Marketing'),

-- Purchase Order Notifications
(7, 'PO Baru - Purchasing ke Warehouse', 'Purchasing membuat Purchase Order', 'purchase_order_created', 1, NULL, 'head_warehouse,head_purchasing', 'Warehouse,Purchasing', NULL, NULL, 1, 'PO Baru: {{po_number}}', 'Purchase Order {{po_number}} untuk vendor {{vendor}} dengan nilai {{amount}}', 'po', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Purchasing ke Warehouse & Head Purchasing'),
(8, 'PO Disetujui', 'PO disetujui', 'po_approved', 1, NULL, 'head_warehouse,staff_warehouse,head_purchasing,staff_purchasing', 'Warehouse,Purchasing', NULL, NULL, 1, 'PO Disetujui: {{po_number}}', 'Purchase Order {{po_number}} telah disetujui', 'po', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifikasi ke semua pihak'),
(9, 'PO Ditolak - Head ke Staff', 'PO ditolak', 'po_rejected', 1, NULL, 'head_purchasing,staff_purchasing', 'Purchasing', NULL, NULL, 1, 'PO Ditolak: {{po_number}}', 'Purchase Order {{po_number}} ditolak. Alasan: {{reason}}', 'po', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Head ke Staff Purchasing'),
(10, 'PO Diterima - Warehouse ke Purchasing', 'Warehouse menerima PO', 'po_received', 1, NULL, 'head_purchasing,staff_purchasing', 'Purchasing', NULL, NULL, 1, 'PO Diterima: {{po_number}}', 'Purchase Order {{po_number}} telah diterima oleh Warehouse', 'po', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Warehouse ke Purchasing'),
(11, 'PO Diverifikasi', 'PO diverifikasi', 'po_verified', 1, NULL, 'head_purchasing', 'Purchasing', NULL, NULL, 1, 'PO Diverifikasi: {{po_number}}', 'Purchase Order {{po_number}} telah diverifikasi oleh Warehouse', 'po', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Warehouse ke Head Purchasing'),

-- Delivery Instruction Notifications
(12, 'DI Baru - Operational ke Service', 'Operational submisi Delivery Instruction', 'di_submitted', 1, NULL, 'head_service,head_warehouse,supervisor_service', 'Service,Warehouse', NULL, NULL, 1, 'DI Baru: {{nomor_di}}', 'Delivery Instruction {{nomor_di}} untuk {{pelanggan}}. Unit: {{unit_no}}', 'di', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Operational ke Service & Warehouse'),
(13, 'DI Disetujui - Service ke Operational', 'DI disetujui', 'di_approved', 1, NULL, 'head_operational,staff_operational', 'Operational', NULL, NULL, 1, 'DI Disetujui: {{nomor_di}}', 'Delivery Instruction {{nomor_di}} telah disetujui', 'di', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Service ke Operational'),
(14, 'DI Diproses', 'DI sedang diproses', 'di_in_progress', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'DI Diproses: {{nomor_di}}', 'Delivery Instruction {{nomor_di}} sedang dalam perjalanan', 'di', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Operational ke Service'),
(15, 'DI Selesai - Operational ke Service & Marketing', 'DI delivered/selesai', 'di_delivered', 1, NULL, 'head_service,head_marketing', 'Service,Marketing', NULL, NULL, 1, 'DI Selesai: {{nomor_di}}', 'Delivery Instruction {{nomor_di}} telah selesai', 'di', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Operational ke Service & Marketing'),
(16, 'DI Dibatalkan', 'DI dibatalkan', 'di_cancelled', 1, NULL, 'head_operational,head_service', 'Operational,Service', NULL, NULL, 1, 'DI Dibatalkan: {{nomor_di}}', 'Delivery Instruction {{nomor_di}} dibatalkan', 'di', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifikasi ke semua pihak'),

-- Quotation Notifications
(17, 'Quotation Baru - Staff ke Head', 'Marketing membuat Quotation', 'quotation_created', 1, NULL, 'head_marketing', 'Marketing', NULL, NULL, 1, 'Quotation Baru: {{quotation_number}}', 'Quotation {{quotation_number}} untuk {{customer}}', 'quotation', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Staff ke Head Marketing'),
(18, 'Quotation Disetujui', 'Quotation disetujui', 'quotation_approved', 1, NULL, 'head_marketing,staff_marketing', 'Marketing', NULL, NULL, 1, 'Quotation Disetujui: {{quotation_number}}', 'Quotation {{quotation_number}} telah disetujui', 'quotation', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Head ke Staff Marketing'),
(19, 'Quotation Ditolak', 'Quotation ditolak', 'quotation_rejected', 1, NULL, 'head_marketing,staff_marketing', 'Marketing', NULL, NULL, 1, 'Quotation Ditolak: {{quotation_number}}', 'Quotation {{quotation_number}} ditolak', 'quotation', 'warning', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Head ke Staff Marketing'),
(20, 'Quotation Dikirim ke Customer', 'Quotation dikirim ke customer', 'quotation_sent', 1, NULL, 'head_marketing', 'Marketing', NULL, NULL, 1, 'Quotation Dikirim: {{quotation_number}}', 'Quotation {{quotation_number}} telah dikirim ke {{customer}}', 'quotation', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Staff ke Head Marketing'),
(21, 'Kontrak Baru - Marketing ke Service', 'Kontrak baru dibuat', 'contract_created', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Kontrak Baru: {{contract_number}}', 'Kontrak {{contract_number}} untuk {{customer}}', 'quotation', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Marketing ke Service'),
(22, 'Kontrak Akan Expiring', 'Kontrak akan expired', 'contract_expiring', 1, NULL, 'head_marketing,staff_marketing', 'Marketing', NULL, NULL, 1, 'Kontrak Expiring: {{contract_number}}', 'Kontrak {{contract_number}} akan expired pada {{expired_date}}', 'quotation', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Reminder ke Marketing'),
(23, 'Kontrak Expired', 'Kontrak expired', 'contract_expired', 1, NULL, 'head_marketing,staff_marketing', 'Marketing', NULL, NULL, 1, 'Kontrak Expired: {{contract_number}}', 'Kontrak {{contract_number}} telah expired', 'quotation', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing'),

-- Invoice Notifications
(24, 'Invoice Baru - Accounting ke Marketing', 'Invoice dibuat', 'invoice_created', 1, NULL, 'head_marketing,head_accounting', 'Marketing,Accounting', NULL, NULL, 1, 'Invoice Baru: {{invoice_number}}', 'Invoice {{invoice_number}} untuk {{customer}} sebesar {{amount}}', 'invoice', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Accounting ke Marketing'),
(25, 'Invoice Dikirim ke Customer', 'Invoice dikirim ke customer', 'invoice_sent', 1, NULL, 'head_accounting,staff_accounting', 'Accounting', NULL, NULL, 1, 'Invoice Dikirim: {{invoice_number}}', 'Invoice {{invoice_number}} telah dikirim ke {{customer}}', 'invoice', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Dari Staff ke Head Accounting'),
(26, 'Invoice Lunas', 'Invoice lunas', 'invoice_paid', 1, NULL, 'head_marketing,head_accounting', 'Marketing,Accounting', NULL, NULL, 1, 'Invoice Lunas: {{invoice_number}}', 'Invoice {{invoice_number}} telah dibayar lunas', 'invoice', 'success', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke semua pihak'),
(27, 'Invoice Overdue', 'Invoice overdue', 'invoice_overdue', 1, NULL, 'head_marketing,head_accounting', 'Marketing,Accounting', NULL, NULL, 1, 'Invoice Overdue: {{invoice_number}}', 'Invoice {{invoice_number}} telah jatuh tempo', 'invoice', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Reminder ke semua pihak'),
(28, 'Pembayaran Diterima', 'Pembayaran diterima', 'payment_received', 1, NULL, 'head_marketing,head_accounting', 'Marketing,Accounting', NULL, NULL, 1, 'Pembayaran Diterima: {{invoice_number}}', 'Pembayaran untuk invoice {{invoice_number}} telah diterima', 'invoice', 'success', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Accounting'),

-- Inventory Notifications
(29, 'Unit Baru Masuk Inventory', 'Unit baru masuk inventory', 'inventory_unit_added', 1, NULL, 'head_warehouse,head_marketing,head_service', 'Warehouse,Marketing,Service', NULL, NULL, 1, 'Unit Baru: {{unit_no}}', 'Unit {{unit_no}} ({{model}}) telah masuk inventory', 'inventory', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Warehouse, Marketing, Service'),
(30, 'Unit Stock Rendah', 'Unit stock rendah', 'inventory_unit_low_stock', 1, NULL, 'head_warehouse,head_marketing', 'Warehouse,Marketing', NULL, NULL, 1, 'Unit Stock Rendah: {{unit_no}}', 'Unit {{unit_no}} stock rendah', 'inventory', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Warning ke Warehouse & Marketing'),
(31, 'Unit Disewa', 'Unit mulai disewa', 'inventory_unit_rented', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Unit Disewa: {{unit_no}}', 'Unit {{unit_no}} mulai disewa oleh {{customer}}', 'inventory', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Service'),
(32, 'Unit Dikembalikan', 'Unit dikembalikan', 'inventory_unit_returned', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Unit Dikembalikan: {{unit_no}}', 'Unit {{unit_no}} telah dikembalikan', 'inventory', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Service'),
(33, 'Unit Maintenance', 'Unit masuk maintenance', 'inventory_unit_maintenance', 1, NULL, 'head_warehouse,head_service', 'Warehouse,Service', NULL, NULL, 1, 'Unit Maintenance: {{unit_no}}', 'Unit {{unit_no}} masuk maintenance', 'inventory', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Warehouse & Service'),

-- Delivery Notifications
(34, 'Delivery Baru', 'Delivery dibuat', 'delivery_created', 1, NULL, 'head_service,head_marketing', 'Service,Marketing', NULL, NULL, 1, 'Delivery Baru: {{delivery_number}}', 'Delivery {{delivery_number}} untuk {{customer}}', 'delivery', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Service & Marketing'),
(35, 'Delivery Dalam Perjalanan', 'Delivery dalam perjalanan', 'delivery_in_transit', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Delivery Dalam Perjalanan: {{delivery_number}}', 'Delivery {{delivery_number}} sedang dalam perjalanan', 'delivery', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Service'),
(36, 'Delivery Tiba', 'Delivery tiba', 'delivery_arrived', 1, NULL, 'head_marketing', 'Marketing', NULL, NULL, 1, 'Delivery Tiba: {{delivery_number}}', 'Delivery {{delivery_number}} telah tiba di tujuan', 'delivery', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing'),
(37, 'Delivery Selesai', 'Delivery selesai', 'delivery_completed', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Delivery Selesai: {{delivery_number}}', 'Delivery {{delivery_number}} telah selesai', 'delivery', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Service'),
(38, 'Delivery Terlambat', 'Delivery terlambat', 'delivery_delayed', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Delivery Terlambat: {{delivery_number}}', 'Delivery {{delivery_number}} terlambat', 'delivery', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Warning ke Marketing & Service'),

-- Sparepart Notifications
(39, 'Sparepart Baru', 'Sparepart baru ditambahkan', 'sparepart_added', 1, NULL, 'head_warehouse,head_service', 'Warehouse,Service', NULL, NULL, 1, 'Sparepart Baru: {{part_number}}', 'Sparepart {{part_number}} ({{part_name}}) ditambahkan', 'sparepart', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Warehouse & Service'),
(40, 'Sparepart Stock Rendah', 'Sparepart stock rendah', 'sparepart_low_stock', 1, NULL, 'head_warehouse,head_service', 'Warehouse,Service', NULL, NULL, 1, 'Sparepart Stock Rendah: {{part_number}}', 'Sparepart {{part_number}} stock rendah', 'sparepart', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Warning ke Warehouse & Service'),
(41, 'Sparepart Habis', 'Sparepart habis', 'sparepart_out_of_stock', 1, NULL, 'head_warehouse,head_service,head_purchasing', 'Warehouse,Service,Purchasing', NULL, NULL, 1, 'Sparepart Habis: {{part_number}}', 'Sparepart {{part_number}} habis stock', 'sparepart', 'error', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Critical ke semua pihak'),
(42, 'Sparepart Digunakan', 'Sparepart digunakan', 'sparepart_used', 1, NULL, 'head_warehouse,staff_warehouse', 'Warehouse', NULL, NULL, 1, 'Sparepart Digunakan: {{part_number}}', 'Sparepart {{part_number}} digunakan untuk {{reference}}', 'sparepart', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Warehouse'),

-- User Management Notifications
(43, 'User Baru Dibuat', 'User baru dibuat', 'user_created', 1, NULL, 'head_hrd,head_it,administrator', 'HRD,Administrator', NULL, NULL, 1, 'User Baru: {{username}}', 'User {{username}} telah dibuat dengan role {{role}}', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke HRD & IT'),
(44, 'User Diaktifkan', 'User diaktifkan', 'user_activated', 1, NULL, 'head_hrd', 'HRD', NULL, NULL, 1, 'User Aktif: {{username}}', 'User {{username}} telah diaktifkan', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke HRD'),
(45, 'User Dinonaktifkan', 'User dinonaktifkan', 'user_deactivated', 1, NULL, 'head_hrd', 'HRD', NULL, NULL, 1, 'User Nonaktif: {{username}}', 'User {{username}} telah dinonaktifkan', 'user', 'warning', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke HRD'),
(46, 'Role Baru Dibuat', 'Role baru dibuat', 'role_created', 1, NULL, 'head_hrd,administrator', 'HRD,Administrator', NULL, NULL, 1, 'Role Baru: {{role_name}}', 'Role {{role_name}} telah dibuat', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke HRD & Admin'),
(47, 'Permission Diubah', 'Permission diubah', 'permission_changed', 1, NULL, NULL, NULL, NULL, NULL, 0, 'Permission Diubah', 'Permission Anda telah diubah', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke user terkait'),
(48, 'Employee Ditugaskan', 'Employee ditugaskan', 'employee_assigned', 1, NULL, NULL, NULL, NULL, NULL, 1, 'Employee Ditugaskan: {{employee_name}}', '{{employee_name}} ditugaskan ke divisi {{division}}', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Head Division'),
(49, 'Employee Dilepas', 'Employee dilepas', 'employee_unassigned', 1, NULL, NULL, NULL, NULL, NULL, 1, 'Employee Dilepas: {{employee_name}}', '{{employee_name}} dilepas dari divisi {{division}}', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Head Division'),

-- Supplier Notifications
(50, 'Supplier Baru', 'Supplier baru dibuat', 'supplier_created', 1, NULL, 'head_purchasing,head_warehouse', 'Purchasing,Warehouse', NULL, NULL, 1, 'Supplier Baru: {{supplier_name}}', 'Supplier {{supplier_name}} telah ditambahkan', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Purchasing & Warehouse'),
(51, 'Supplier Diupdate', 'Supplier diupdate', 'supplier_updated', 1, NULL, 'head_purchasing', 'Purchasing', NULL, NULL, 1, 'Supplier Diupdate: {{supplier_name}}', 'Supplier {{supplier_name}} telah diupdate', 'user', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Purchasing'),

-- PMPS Notifications
(52, 'PMPS Akan Jatuh Tempo', 'PMPS akan jatuh tempo', 'pmps_due_soon', 1, NULL, 'head_service,staff_service,head_marketing', 'Service,Marketing', NULL, NULL, 1, 'PMPS Akan Jatuh Tempo: {{unit_no}}', 'PMPS untuk unit {{unit_no}} akan jatuh tempo', 'service', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Reminder ke Service & Marketing'),
(53, 'PMPS Overdue', 'PMPS overdue', 'pmps_overdue', 1, NULL, 'head_service,head_marketing', 'Service,Marketing', NULL, NULL, 1, 'PMPS Overdue: {{unit_no}}', 'PMPS untuk unit {{unit_no}} overdue', 'service', 'error', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Warning ke Service & Marketing'),
(54, 'PMPS Selesai', 'PMPS selesai', 'pmps_completed', 1, NULL, 'head_marketing', 'Marketing', NULL, NULL, 1, 'PMPS Selesai: {{unit_no}}', 'PMPS untuk unit {{unit_no}} telah selesai', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing'),

-- Service Notifications
(55, 'Verifikasi Unit Disimpan', 'Unit verification disimpan', 'unit_verification_saved', 1, NULL, 'head_service,head_warehouse', 'Service,Warehouse', NULL, NULL, 1, 'Verifikasi Unit: {{unit_no}}', 'Verifikasi unit {{unit_no}} telah disimpan', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Service & Warehouse'),
(56, 'Lokasi Unit Diperbarui', 'Lokasi unit diperbarui', 'unit_location_updated', 1, NULL, 'head_marketing,head_service', 'Marketing,Service', NULL, NULL, 1, 'Lokasi Unit Diupdate: {{unit_no}}', 'Lokasi unit {{unit_no}} diperbarui ke {{location}}', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Marketing & Service'),
(57, 'Work Order Baru', 'Work Order dibuat', 'work_order_created', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'Work Order Baru: {{wo_number}}', 'Work Order {{wo_number}} telah dibuat', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Head/Supervisor Service'),
(58, 'Work Order Ditugaskan', 'Work Order ditugaskan', 'work_order_assigned', 1, NULL, 'staff_service', 'Service', NULL, NULL, 1, 'Work Order Ditugaskan: {{wo_number}}', 'Work Order {{wo_number}} ditugaskan ke Anda', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Staff'),
(59, 'Work Order Dimulai', 'Work Order dimulai', 'work_order_in_progress', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'Work Order Dimulai: {{wo_number}}', 'Work Order {{wo_number}} sedang dikerjakan', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Head/Supervisor'),
(60, 'Work Order Selesai', 'Work Order selesai', 'work_order_completed', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'Work Order Selesai: {{wo_number}}', 'Work Order {{wo_number}} telah selesai', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Head/Supervisor'),
(61, 'Work Order Dibatalkan', 'Work Order dibatalkan', 'work_order_cancelled', 1, NULL, 'head_service,supervisor_service', 'Service', NULL, NULL, 1, 'Work Order Dibatalkan: {{wo_number}}', 'Work Order {{wo_number}} dibatalkan', 'service', 'warning', 3, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Warning ke Head/Supervisor'),
(62, 'Penugasan Service Baru', 'Penugasan Service dibuat', 'service_assignment_created', 1, NULL, 'staff_service,supervisor_service', 'Service', NULL, NULL, 1, 'Penugasan Baru: {{assignment_number}}', 'Penugasan {{assignment_number}} telah dibuat', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Staff'),
(63, 'Penugasan Service Diupdate', 'Penugasan Service diupdate', 'service_assignment_updated', 1, NULL, 'supervisor_service', 'Service', NULL, NULL, 1, 'Penugasan Diupdate: {{assignment_number}}', 'Penugasan {{assignment_number}} telah diupdate', 'service', 'info', 2, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke Supervisor'),

-- System Notifications
(64, 'Attachment Ditambahkan', 'Attachment ditambahkan', 'attachment_added', 1, NULL, NULL, NULL, NULL, NULL, 0, 'Attachment Ditambahkan', 'Attachment {{filename}} ditambahkan', 'system', 'info', 1, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifier ke user terkait'),
(65, 'Notifikasi Sistem', 'Notifikasi sistem umum', 'system_notification', 1, NULL, NULL, NULL, NULL, NULL, 0, '{{title}}', '{{message}}', 'system', 'info', 1, 'info_only', '', 0, 30, NULL, NOW(), NOW(), 1, NULL, 'Notifikasi sistem umum');

-- Step 3: Verify data
SELECT COUNT(*) AS total_rules FROM notification_rules;
SELECT trigger_event, name, target_roles, notification_style FROM notification_rules ORDER BY id;
