<?= $this->extend('layouts/base') ?>

<?= $this->section('content') ?>
<?php
$repStatus = (string) ($report['status'] ?? '');
$statusBadgeClass = match ($repStatus) {
    'completed' => 'success',
    'failed' => 'danger',
    'pending', 'processing' => 'warning',
    default => 'secondary',
};
$genName = trim((string) ($report['first_name'] ?? '') . ' ' . (string) ($report['last_name'] ?? ''));
?>

<div class="container-fluid">
    <!-- Page Header -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            <i class="fas fa-file-alt me-2"></i><?= esc($report['name']) ?>
        </h1>
        <div class="d-sm-flex align-items-center">
            <div class="btn-group" role="group">
                <a href="<?= base_url('reports') ?>" class="btn btn-outline-secondary btn-sm">
                    <i class="fas fa-arrow-left me-1"></i>Back to Reports
                </a>
                <?php if ($repStatus === 'completed'): ?>
                    <a href="<?= base_url('reports/download/' . $report['id']) ?>" class="btn btn-primary btn-sm">
                        <i class="fas fa-download me-1"></i>Download
                    </a>
                <?php endif; ?>
                <button class="btn btn-outline-danger btn-sm" onclick="deleteReport(<?= $report['id'] ?>)">
                    <i class="fas fa-trash me-1"></i>Delete
                </button>
            </div>
        </div>
    </div>

    <!-- Report Information -->
    <div class="row mb-4">
        <div class="col-lg-8">
            <div class="card shadow">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        <i class="fas fa-info-circle me-2"></i>Report Information
                    </h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <td class="fw-bold">Report Name:</td>
                                    <td><?= esc($report['name']) ?></td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Report Type:</td>
                                    <td>
                                        <span class="badge badge-primary"><?= esc(ucfirst(str_replace('_', ' ', $report['type']))) ?></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Format:</td>
                                    <td>
                                        <span class="badge badge-info"><?= strtoupper($report['format']) ?></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Status:</td>
                                    <td>
                                        <span class="badge badge-<?= esc($statusBadgeClass, 'attr') ?>">
                                            <?= esc(ucfirst($repStatus)) ?>
                                        </span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <td class="fw-bold">Generated By:</td>
                                    <td><?= esc(trim(($report['first_name'] ?? '') . ' ' . ($report['last_name'] ?? '')) ?: 'System') ?></td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Created At:</td>
                                    <td><?= !empty($report['created_at']) ? date('d F Y, H:i:s', strtotime($report['created_at'])) : '-' ?></td>
                                </tr>
                                <?php if (!empty($report['completed_at'])): ?>
                                <tr>
                                    <td class="fw-bold">Completed At:</td>
                                    <td><?= date('d F Y, H:i:s', strtotime($report['completed_at'])) ?></td>
                                </tr>
                                <?php endif; ?>
                                <?php if (!empty($report['updated_at']) && $repStatus === 'completed'): ?>
                                <tr>
                                    <td class="fw-bold">Finished At:</td>
                                    <td><?= date('d F Y, H:i:s', strtotime($report['updated_at'])) ?></td>
                                </tr>
                                <?php endif; ?>
                                <?php if ($report['filename']): ?>
                                <tr>
                                    <td class="fw-bold">File Size:</td>
                                    <td>
                                        <?php
                                        $filepath = !empty($report['file_path']) && is_file($report['file_path'])
                                            ? $report['file_path']
                                            : (WRITEPATH . 'reports/' . ($report['filename'] ?? ''));
                                        if (is_string($filepath) && file_exists($filepath)) {
                                            echo formatBytes(filesize($filepath));
                                        } else {
                                            echo 'File not found';
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <?php endif; ?>
                            </table>
                        </div>
                    </div>
                    
                    <?php if (!empty($report['description'])): ?>
                    <div class="mt-3">
                        <h6 class="fw-bold">Description:</h6>
                        <p class="text-muted"><?= esc($report['description']) ?></p>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        
        <div class="col-lg-4">
            <div class="card shadow">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-success">
                        <i class="fas fa-chart-pie me-2"></i>Report Statistics
                    </h6>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <?php if ($repStatus === 'completed'): ?>
                            <div class="mb-3">
                                <i class="fas fa-check-circle fa-3x text-success"></i>
                            </div>
                            <h5 class="text-success">Report Completed</h5>
                            <p class="text-muted">Your report has been generated successfully and is ready for download.</p>
                            
                            <?php if ($report['filename']): ?>
                            <div class="mt-3">
                                <a href="<?= base_url('reports/download/' . $report['id']) ?>" 
                                   class="btn btn-success btn-lg">
                                    <i class="fas fa-download me-2"></i>Download Report
                                </a>
                            </div>
                            <?php endif; ?>
                            
                        <?php elseif (in_array($repStatus, ['pending', 'processing'], true)): ?>
                            <div class="mb-3">
                                <div class="spinner-border text-warning" role="status">
                                    <span class="visually-hidden">Loading...</span>
                                </div>
                            </div>
                            <h5 class="text-warning">Report in progress</h5>
                            <p class="text-muted">Your report is being generated. Refresh this page in a moment.</p>
                            
                            <div class="mt-3">
                                <button class="btn btn-outline-primary" onclick="refreshPage()">
                                    <i class="fas fa-sync-alt me-2"></i>Refresh Status
                                </button>
                            </div>
                            
                        <?php elseif ($repStatus === 'failed'): ?>
                            <div class="mb-3">
                                <i class="fas fa-exclamation-triangle fa-3x text-danger"></i>
                            </div>
                            <h5 class="text-danger">Report Failed</h5>
                            <?php
                            $errMsg = $report['error_message'] ?? null;
                            if (empty($errMsg) && !empty($report['parameters'])) {
                                $params = json_decode((string) $report['parameters'], true);
                                $errMsg = $params['_error'] ?? null;
                            }
                            ?>
                            <?php if (!empty($errMsg)): ?>
                            <div class="alert alert-danger text-start small mt-2 mb-2" role="alert">
                                <strong>Error:</strong> <?= esc($errMsg) ?>
                            </div>
                            <?php else: ?>
                            <p class="text-muted">There was an error generating this report. Please try again or contact support.</p>
                            <?php endif; ?>
                            <div class="mt-3">
                                <button class="btn btn-outline-danger" onclick="retryGeneration()">
                                    <i class="fas fa-redo me-2"></i>Retry Generation
                                </button>
                            </div>
                        <?php else: ?>
                            <div class="mb-3">
                                <i class="fas fa-info-circle fa-3x text-secondary"></i>
                            </div>
                            <h5 class="text-secondary">Unknown status</h5>
                            <p class="text-muted">Refresh the page or return to the reports list.</p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            
            <!-- Quick Actions -->
            <div class="card shadow mt-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-info">
                        <i class="fas fa-bolt me-2"></i>Quick Actions
                    </h6>
                </div>
                <div class="card-body">
                    <div class="d-grid gap-2">
                        <?php if ($repStatus === 'completed'): ?>
                            <button class="btn btn-outline-primary" onclick="regenerateReport()">
                                <i class="fas fa-redo me-2"></i>Regenerate Report
                            </button>
                            <button class="btn btn-outline-info" onclick="shareReport()">
                                <i class="fas fa-share me-2"></i>Share Report
                            </button>
                            <button class="btn btn-outline-success" onclick="emailReport()">
                                <i class="fas fa-envelope me-2"></i>Email Report
                            </button>
                        <?php endif; ?>
                        <button class="btn btn-outline-secondary" onclick="duplicateReport()">
                            <i class="fas fa-copy me-2"></i>Duplicate Report
                        </button>
                        <a href="<?= base_url('reports?section=custom') ?>" class="btn btn-outline-primary">
                            <i class="fas fa-plus me-2"></i>Create New Report
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Report Preview (if available) -->
    <?php if ($repStatus === 'completed' && $report['format'] == 'pdf'): ?>
    <div class="card shadow">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                <i class="fas fa-eye me-2"></i>Report Preview
            </h6>
        </div>
        <div class="card-body">
            <div class="text-center">
                <iframe src="<?= base_url('reports/download/' . $report['id']) ?>" 
                        width="100%" height="600px" 
                        style="border: 1px solid #ddd; border-radius: 5px;">
                    <p>Your browser does not support iframes. 
                       <a href="<?= base_url('reports/download/' . $report['id']) ?>">Download the PDF</a> instead.
                    </p>
                </iframe>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>

<?= $this->endSection() ?>

<?= $this->section('javascript') ?>
<script>
function deleteReport(id) {
    OptimaConfirm.danger({
        title: 'Hapus Report',
        text: 'Apakah Anda yakin ingin menghapus report ini? Tindakan ini tidak dapat dibatalkan.',
        onConfirm: function() {
            var delBody = {};
            if (window.csrfTokenName && window.csrfToken) {
                delBody[window.csrfTokenName] = window.csrfToken;
            }
            $.ajax({
        url: '<?= base_url('reports/delete/') ?>' + id,
        method: 'POST',
        data: delBody,
        dataType: 'json',
        headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
        success: function(response) {
            if (response.success) {
                alertSwal('success', 'Report berhasil dihapus!');
                setTimeout(function() { window.location.href = '<?= base_url('reports') ?>'; }, 1500);
            } else {
                alertSwal('error', response.message, 'Gagal Hapus Report');
            }
        },
        error: function(xhr, status, error) {
            alertSwal('error', 'Error: ' + error);
        }
    });
        }
    });
}

function refreshPage() {
    location.reload();
}

function retryGeneration() {
    showNotification('Retry generation feature coming soon!', 'info');
}

function regenerateReport() {
    OptimaConfirm.generic({
        title: 'Regenerasi Report',
        text: 'Ini akan membuat versi baru dengan data terkini. Lanjutkan?',
        icon: 'info',
        confirmText: '<i class="fas fa-redo me-1"></i>Ya, Regenerasi',
        confirmButtonColor: '#0d6efd',
        onConfirm: function() {
            alertSwal('info', 'Fitur regenerate report akan segera tersedia!');
        }
    });
}

function shareReport() {
    const reportUrl = window.location.href;
    if (navigator.share) {
        navigator.share({
            title: '<?= esc($report['name']) ?>',
            text: 'Check out this report from OPTIMA',
            url: reportUrl
        });
    } else {
        // Fallback: copy to clipboard
        navigator.clipboard.writeText(reportUrl).then(function() {
            showNotification('Report URL copied to clipboard!', 'success');
        });
    }
}

function emailReport() {
    showNotification('Email report feature coming soon!', 'info');
}

function duplicateReport() {
    showNotification('Duplicate report feature coming soon!', 'info');
}

function showNotification(message, type) {
    const alertClass = type === 'success' ? 'alert-success' : 
                      type === 'error' ? 'alert-danger' : 
                      type === 'warning' ? 'alert-warning' : 'alert-info';
    
    const notification = `
        <div class="alert ${alertClass} alert-dismissible fade show" role="alert">
            <strong>${type.charAt(0).toUpperCase() + type.slice(1)}!</strong> ${message}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    `;
    
    $('.container-fluid').prepend(notification);
    
    setTimeout(function() {
        $('.alert').fadeOut();
    }, 5000);
}

// Auto-refresh while report is still processing
<?php if (in_array($repStatus, ['pending', 'processing'], true)): ?>
setTimeout(function() {
    location.reload();
}, 10000);
<?php endif; ?>
</script>

<?php
// Helper function for formatting file sizes
if (!function_exists('formatBytes')) {
    function formatBytes($size, $precision = 2) {
        $base = log($size, 1024);
        $suffixes = array('B', 'KB', 'MB', 'GB', 'TB');
        return round(pow(1024, $base - floor($base)), $precision) . ' ' . $suffixes[floor($base)];
    }
}
?>
<?= $this->endSection() ?> 